//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVWebServiceTestProject.SAWebServiceOld {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.pbstest.org/SAWebService", ConfigurationName="SAWebServiceOld.SAWebServiceSoap")]
    public interface SAWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/CloseSessionRequest", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/CloseSessionResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void CloseSession(string strSessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/OpenSessionRequest", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/OpenSessionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        string OpenSession(BVWebServiceTestProject.SAWebServiceOld.UserProfile userProfile);
        
        // CODEGEN: Generating message contract since the wrapper name (ListMediaCutsInfoSession) of message ListMediaCutsInfoSession does not match the default value (ListMediaCutsInfo)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/ListMediaCutsInfoSes" +
            "sion", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/ListMediaCutsInfoSes" +
            "sion")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.ListMediaCutsInfoSession1 ListMediaCutsInfo(BVWebServiceTestProject.SAWebServiceOld.ListMediaCutsInfoSession request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetDetailedAirDateSession) of message GetDetailedAirDateSession does not match the default value (GetDetailedAirDate)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/GetDetailedAirDateSe" +
            "ssion", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/GetDetailedAirDateSe" +
            "ssion")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.GetDetailedAirDateSession1 GetDetailedAirDate(BVWebServiceTestProject.SAWebServiceOld.GetDetailedAirDateSession request);
        
        // CODEGEN: Generating message contract since the wrapper name (ListPackageCutsInfoSession) of message ListPackageCutsInfoSession does not match the default value (ListPackageCutsInfo)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/ListPackageCutsInfoS" +
            "ession", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/ListPackageCutsInfoS" +
            "ession")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.ListPackageCutsInfoSession1 ListPackageCutsInfo(BVWebServiceTestProject.SAWebServiceOld.ListPackageCutsInfoSession request);
        
        // CODEGEN: Generating message contract since the wrapper name (ListPackageMediaInfoSession) of message ListPackageMediaInfoSession does not match the default value (ListPackageMediaInfo)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/ListPackageMediaInfo" +
            "Session", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/ListPackageMediaInfo" +
            "Session")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.ListPackageMediaInfoSession1 ListPackageMediaInfo(BVWebServiceTestProject.SAWebServiceOld.ListPackageMediaInfoSession request);
        
        // CODEGEN: Generating message contract since the wrapper name (SearchMediaAirDateSession) of message SearchMediaAirDateSession does not match the default value (SearchMediaAirDate)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchMediaAirDateSe" +
            "ssion", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchMediaAirDateSe" +
            "ssion")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.SearchMediaAirDateSession1 SearchMediaAirDate(BVWebServiceTestProject.SAWebServiceOld.SearchMediaAirDateSession request);
        
        // CODEGEN: Generating message contract since the wrapper name (SearchPackageAirDateSession) of message SearchPackageAirDateSession does not match the default value (SearchPackageAirDate)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchPackageAirDate" +
            "Session", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchPackageAirDate" +
            "Session")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.SearchPackageAirDateSession1 SearchPackageAirDate(BVWebServiceTestProject.SAWebServiceOld.SearchPackageAirDateSession request);
        
        // CODEGEN: Generating message contract since the wrapper name (SearchMediaInfoSession) of message SearchMediaInfoSession does not match the default value (SearchMediaInfo)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchMediaInfoSessi" +
            "on", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchMediaInfoSessi" +
            "on")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.SearchMediaInfoSession1 SearchMediaInfo(BVWebServiceTestProject.SAWebServiceOld.SearchMediaInfoSession request);
        
        // CODEGEN: Generating message contract since the wrapper name (SearchPackageInfoSession) of message SearchPackageInfoSession does not match the default value (SearchPackageInfo)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchPackageInfoSes" +
            "sion", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchPackageInfoSes" +
            "sion")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.SearchPackageInfoSession1 SearchPackageInfo(BVWebServiceTestProject.SAWebServiceOld.SearchPackageInfoSession request);
        
        // CODEGEN: Generating message contract since the wrapper name (ListMediaCutsInfo) of message ListMediaCutsInfoRequest does not match the default value (ListMediaCutsInfo1)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/ListMediaCutsInfoReq" +
            "uest", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/ListMediaCutsInfoRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.ListMediaCutsInfoResponse ListMediaCutsInfo1(BVWebServiceTestProject.SAWebServiceOld.ListMediaCutsInfoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetDetailedAirDate) of message GetDetailedAirDateRequest does not match the default value (GetDetailedAirDate1)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/GetDetailedAirDateRe" +
            "quest", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/GetDetailedAirDateRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.GetDetailedAirDateResponse GetDetailedAirDate1(BVWebServiceTestProject.SAWebServiceOld.GetDetailedAirDateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ListPackageCutsInfo) of message ListPackageCutsInfoRequest does not match the default value (ListPackageCutsInfo1)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/ListPackageCutsInfoR" +
            "equest", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/ListPackageCutsInfoR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.ListPackageCutsInfoResponse ListPackageCutsInfo1(BVWebServiceTestProject.SAWebServiceOld.ListPackageCutsInfoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ListPackageMediaInfo) of message ListPackageMediaInfoRequest does not match the default value (ListPackageMediaInfo1)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/ListPackageMediaInfo" +
            "Request", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/ListPackageMediaInfo" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.ListPackageMediaInfoResponse ListPackageMediaInfo1(BVWebServiceTestProject.SAWebServiceOld.ListPackageMediaInfoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SearchMediaAirDate) of message SearchMediaAirDateRequest does not match the default value (SearchMediaAirDate1)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchMediaAirDateRe" +
            "quest", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchMediaAirDateRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.SearchMediaAirDateResponse SearchMediaAirDate1(BVWebServiceTestProject.SAWebServiceOld.SearchMediaAirDateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SearchPackageAirDate) of message SearchPackageAirDateRequest does not match the default value (SearchPackageAirDate1)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchPackageAirDate" +
            "Request", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchPackageAirDate" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.SearchPackageAirDateResponse SearchPackageAirDate1(BVWebServiceTestProject.SAWebServiceOld.SearchPackageAirDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchFeatureAirDate" +
            "Request", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchFeatureAirDate" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        string SearchFeatureAirDate(int intFeatureMediaInventoryID, int nTune_value);
        
        // CODEGEN: Generating message contract since the wrapper name (SearchMediaInfo) of message SearchMediaInfoRequest does not match the default value (SearchMediaInfo1)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchMediaInfoReque" +
            "st", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchMediaInfoRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.SearchMediaInfoResponse SearchMediaInfo1(BVWebServiceTestProject.SAWebServiceOld.SearchMediaInfoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SearchPackageInfo) of message SearchPackageInfoRequest does not match the default value (SearchPackageInfo1)
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchPackageInfoReq" +
            "uest", ReplyAction="http://webservices.pbstest.org/SAWebService/SAWebServiceSoap/SearchPackageInfoRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        BVWebServiceTestProject.SAWebServiceOld.SearchPackageInfoResponse SearchPackageInfo1(BVWebServiceTestProject.SAWebServiceOld.SearchPackageInfoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.pbstest.org/SAWebService")]
    public partial class UserProfile : UserProfileBase {
        
        private string[] oOperatingGroupField;
        
        private short nOperatingUnitField;
        
        private short nUnitTypeField;
        
        private short nRoleField;
        
        private string sExternalEmailField;
        
        private string sPhoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("sCode")]
        public string[] oOperatingGroup {
            get {
                return this.oOperatingGroupField;
            }
            set {
                this.oOperatingGroupField = value;
                this.RaisePropertyChanged("oOperatingGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short nOperatingUnit {
            get {
                return this.nOperatingUnitField;
            }
            set {
                this.nOperatingUnitField = value;
                this.RaisePropertyChanged("nOperatingUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public short nUnitType {
            get {
                return this.nUnitTypeField;
            }
            set {
                this.nUnitTypeField = value;
                this.RaisePropertyChanged("nUnitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public short nRole {
            get {
                return this.nRoleField;
            }
            set {
                this.nRoleField = value;
                this.RaisePropertyChanged("nRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sExternalEmail {
            get {
                return this.sExternalEmailField;
            }
            set {
                this.sExternalEmailField = value;
                this.RaisePropertyChanged("sExternalEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sPhoneNumber {
            get {
                return this.sPhoneNumberField;
            }
            set {
                this.sPhoneNumberField = value;
                this.RaisePropertyChanged("sPhoneNumber");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserProfile))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.pbstest.org/SAWebService")]
    public partial class UserProfileBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sConnectIdField;
        
        private string sFirstNameField;
        
        private string sLastNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sConnectId {
            get {
                return this.sConnectIdField;
            }
            set {
                this.sConnectIdField = value;
                this.RaisePropertyChanged("sConnectId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sFirstName {
            get {
                return this.sFirstNameField;
            }
            set {
                this.sFirstNameField = value;
                this.RaisePropertyChanged("sFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sLastName {
            get {
                return this.sLastNameField;
            }
            set {
                this.sLastNameField = value;
                this.RaisePropertyChanged("sLastName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.pbstest.org/SAWebService")]
    public partial class SearchCriterion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string searchFieldField;
        
        private string searchValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SearchField {
            get {
                return this.searchFieldField;
            }
            set {
                this.searchFieldField = value;
                this.RaisePropertyChanged("SearchField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SearchValue {
            get {
                return this.searchValueField;
            }
            set {
                this.searchValueField = value;
                this.RaisePropertyChanged("SearchValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListMediaCutsInfoSession", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class ListMediaCutsInfoSession {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public string strSessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=1)]
        public BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=2)]
        public int nMaxRow;
        
        public ListMediaCutsInfoSession() {
        }
        
        public ListMediaCutsInfoSession(string strSessionID, BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            this.strSessionID = strSessionID;
            this.searchCriteria = searchCriteria;
            this.nMaxRow = nMaxRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListMediaCutsInfoSessionResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class ListMediaCutsInfoSession1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public System.Data.DataSet ListMediaCutsInfoSessionResult;
        
        public ListMediaCutsInfoSession1() {
        }
        
        public ListMediaCutsInfoSession1(System.Data.DataSet ListMediaCutsInfoSessionResult) {
            this.ListMediaCutsInfoSessionResult = ListMediaCutsInfoSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDetailedAirDateSession", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class GetDetailedAirDateSession {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public string strSessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=1)]
        public int nMediaInventoryId;
        
        public GetDetailedAirDateSession() {
        }
        
        public GetDetailedAirDateSession(string strSessionID, int nMediaInventoryId) {
            this.strSessionID = strSessionID;
            this.nMediaInventoryId = nMediaInventoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDetailedAirDateSessionResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class GetDetailedAirDateSession1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public System.Data.DataSet GetDetailedAirDateSessionResult;
        
        public GetDetailedAirDateSession1() {
        }
        
        public GetDetailedAirDateSession1(System.Data.DataSet GetDetailedAirDateSessionResult) {
            this.GetDetailedAirDateSessionResult = GetDetailedAirDateSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPackageCutsInfoSession", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class ListPackageCutsInfoSession {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public string strSessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=1)]
        public BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=2)]
        public int nMaxRow;
        
        public ListPackageCutsInfoSession() {
        }
        
        public ListPackageCutsInfoSession(string strSessionID, BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            this.strSessionID = strSessionID;
            this.searchCriteria = searchCriteria;
            this.nMaxRow = nMaxRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPackageCutsInfoSessionResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class ListPackageCutsInfoSession1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public System.Data.DataSet ListPackageCutsInfoSessionResult;
        
        public ListPackageCutsInfoSession1() {
        }
        
        public ListPackageCutsInfoSession1(System.Data.DataSet ListPackageCutsInfoSessionResult) {
            this.ListPackageCutsInfoSessionResult = ListPackageCutsInfoSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPackageMediaInfoSession", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class ListPackageMediaInfoSession {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public string strSessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=1)]
        public BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=2)]
        public int nMaxRow;
        
        public ListPackageMediaInfoSession() {
        }
        
        public ListPackageMediaInfoSession(string strSessionID, BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            this.strSessionID = strSessionID;
            this.searchCriteria = searchCriteria;
            this.nMaxRow = nMaxRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPackageMediaInfoSessionResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class ListPackageMediaInfoSession1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public System.Data.DataSet ListPackageMediaInfoSessionResult;
        
        public ListPackageMediaInfoSession1() {
        }
        
        public ListPackageMediaInfoSession1(System.Data.DataSet ListPackageMediaInfoSessionResult) {
            this.ListPackageMediaInfoSessionResult = ListPackageMediaInfoSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchMediaAirDateSession", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchMediaAirDateSession {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public string strSessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=1)]
        public string strMediaHouseNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=2)]
        public int nTune_value;
        
        public SearchMediaAirDateSession() {
        }
        
        public SearchMediaAirDateSession(string strSessionID, string strMediaHouseNumber, int nTune_value) {
            this.strSessionID = strSessionID;
            this.strMediaHouseNumber = strMediaHouseNumber;
            this.nTune_value = nTune_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchMediaAirDateSessionResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchMediaAirDateSession1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public string SearchMediaAirDateSessionResult;
        
        public SearchMediaAirDateSession1() {
        }
        
        public SearchMediaAirDateSession1(string SearchMediaAirDateSessionResult) {
            this.SearchMediaAirDateSessionResult = SearchMediaAirDateSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchPackageAirDateSession", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchPackageAirDateSession {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public string strSessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=1)]
        public string strPackageNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=2)]
        public int nTune_value;
        
        public SearchPackageAirDateSession() {
        }
        
        public SearchPackageAirDateSession(string strSessionID, string strPackageNumber, int nTune_value) {
            this.strSessionID = strSessionID;
            this.strPackageNumber = strPackageNumber;
            this.nTune_value = nTune_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchPackageAirDateSessionResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchPackageAirDateSession1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public string SearchPackageAirDateSessionResult;
        
        public SearchPackageAirDateSession1() {
        }
        
        public SearchPackageAirDateSession1(string SearchPackageAirDateSessionResult) {
            this.SearchPackageAirDateSessionResult = SearchPackageAirDateSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchMediaInfoSession", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchMediaInfoSession {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public string strSessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=1)]
        public BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=2)]
        public int nMaxRow;
        
        public SearchMediaInfoSession() {
        }
        
        public SearchMediaInfoSession(string strSessionID, BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            this.strSessionID = strSessionID;
            this.searchCriteria = searchCriteria;
            this.nMaxRow = nMaxRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchMediaInfoSessionResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchMediaInfoSession1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public System.Data.DataSet SearchMediaInfoSessionResult;
        
        public SearchMediaInfoSession1() {
        }
        
        public SearchMediaInfoSession1(System.Data.DataSet SearchMediaInfoSessionResult) {
            this.SearchMediaInfoSessionResult = SearchMediaInfoSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchPackageInfoSession", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchPackageInfoSession {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public string strSessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=1)]
        public BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=2)]
        public int nMaxRow;
        
        public SearchPackageInfoSession() {
        }
        
        public SearchPackageInfoSession(string strSessionID, BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            this.strSessionID = strSessionID;
            this.searchCriteria = searchCriteria;
            this.nMaxRow = nMaxRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchPackageInfoSessionResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchPackageInfoSession1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public System.Data.DataSet SearchPackageInfoSessionResult;
        
        public SearchPackageInfoSession1() {
        }
        
        public SearchPackageInfoSession1(System.Data.DataSet SearchPackageInfoSessionResult) {
            this.SearchPackageInfoSessionResult = SearchPackageInfoSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListMediaCutsInfo", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class ListMediaCutsInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=1)]
        public int nMaxRow;
        
        public ListMediaCutsInfoRequest() {
        }
        
        public ListMediaCutsInfoRequest(BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            this.searchCriteria = searchCriteria;
            this.nMaxRow = nMaxRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListMediaCutsInfoResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class ListMediaCutsInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public System.Data.DataSet ListMediaCutsInfoResult;
        
        public ListMediaCutsInfoResponse() {
        }
        
        public ListMediaCutsInfoResponse(System.Data.DataSet ListMediaCutsInfoResult) {
            this.ListMediaCutsInfoResult = ListMediaCutsInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDetailedAirDate", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class GetDetailedAirDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public int nMediaInventoryId;
        
        public GetDetailedAirDateRequest() {
        }
        
        public GetDetailedAirDateRequest(int nMediaInventoryId) {
            this.nMediaInventoryId = nMediaInventoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDetailedAirDateResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class GetDetailedAirDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public System.Data.DataSet GetDetailedAirDateResult;
        
        public GetDetailedAirDateResponse() {
        }
        
        public GetDetailedAirDateResponse(System.Data.DataSet GetDetailedAirDateResult) {
            this.GetDetailedAirDateResult = GetDetailedAirDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPackageCutsInfo", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class ListPackageCutsInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=1)]
        public int nMaxRow;
        
        public ListPackageCutsInfoRequest() {
        }
        
        public ListPackageCutsInfoRequest(BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            this.searchCriteria = searchCriteria;
            this.nMaxRow = nMaxRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPackageCutsInfoResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class ListPackageCutsInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public System.Data.DataSet ListPackageCutsInfoResult;
        
        public ListPackageCutsInfoResponse() {
        }
        
        public ListPackageCutsInfoResponse(System.Data.DataSet ListPackageCutsInfoResult) {
            this.ListPackageCutsInfoResult = ListPackageCutsInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPackageMediaInfo", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class ListPackageMediaInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=1)]
        public int nMaxRow;
        
        public ListPackageMediaInfoRequest() {
        }
        
        public ListPackageMediaInfoRequest(BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            this.searchCriteria = searchCriteria;
            this.nMaxRow = nMaxRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPackageMediaInfoResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class ListPackageMediaInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public System.Data.DataSet ListPackageMediaInfoResult;
        
        public ListPackageMediaInfoResponse() {
        }
        
        public ListPackageMediaInfoResponse(System.Data.DataSet ListPackageMediaInfoResult) {
            this.ListPackageMediaInfoResult = ListPackageMediaInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchMediaAirDate", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchMediaAirDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public string strMediaHouseNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=1)]
        public int nTune_value;
        
        public SearchMediaAirDateRequest() {
        }
        
        public SearchMediaAirDateRequest(string strMediaHouseNumber, int nTune_value) {
            this.strMediaHouseNumber = strMediaHouseNumber;
            this.nTune_value = nTune_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchMediaAirDateResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchMediaAirDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public string SearchMediaAirDateResult;
        
        public SearchMediaAirDateResponse() {
        }
        
        public SearchMediaAirDateResponse(string SearchMediaAirDateResult) {
            this.SearchMediaAirDateResult = SearchMediaAirDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchPackageAirDate", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchPackageAirDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public string strPackageNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=1)]
        public int nTune_value;
        
        public SearchPackageAirDateRequest() {
        }
        
        public SearchPackageAirDateRequest(string strPackageNumber, int nTune_value) {
            this.strPackageNumber = strPackageNumber;
            this.nTune_value = nTune_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchPackageAirDateResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchPackageAirDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public string SearchPackageAirDateResult;
        
        public SearchPackageAirDateResponse() {
        }
        
        public SearchPackageAirDateResponse(string SearchPackageAirDateResult) {
            this.SearchPackageAirDateResult = SearchPackageAirDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchMediaInfo", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchMediaInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=1)]
        public int nMaxRow;
        
        public SearchMediaInfoRequest() {
        }
        
        public SearchMediaInfoRequest(BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            this.searchCriteria = searchCriteria;
            this.nMaxRow = nMaxRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchMediaInfoResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchMediaInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public System.Data.DataSet SearchMediaInfoResult;
        
        public SearchMediaInfoResponse() {
        }
        
        public SearchMediaInfoResponse(System.Data.DataSet SearchMediaInfoResult) {
            this.SearchMediaInfoResult = SearchMediaInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchPackageInfo", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchPackageInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=1)]
        public int nMaxRow;
        
        public SearchPackageInfoRequest() {
        }
        
        public SearchPackageInfoRequest(BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            this.searchCriteria = searchCriteria;
            this.nMaxRow = nMaxRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchPackageInfoResponse", WrapperNamespace="http://webservices.pbstest.org/SAWebService", IsWrapped=true)]
    public partial class SearchPackageInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.pbstest.org/SAWebService", Order=0)]
        public System.Data.DataSet SearchPackageInfoResult;
        
        public SearchPackageInfoResponse() {
        }
        
        public SearchPackageInfoResponse(System.Data.DataSet SearchPackageInfoResult) {
            this.SearchPackageInfoResult = SearchPackageInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SAWebServiceSoapChannel : BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SAWebServiceSoapClient : System.ServiceModel.ClientBase<BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap>, BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap {
        
        public SAWebServiceSoapClient() {
        }
        
        public SAWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SAWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CloseSession(string strSessionID) {
            base.Channel.CloseSession(strSessionID);
        }
        
        public string OpenSession(BVWebServiceTestProject.SAWebServiceOld.UserProfile userProfile) {
            return base.Channel.OpenSession(userProfile);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.ListMediaCutsInfoSession1 BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.ListMediaCutsInfo(BVWebServiceTestProject.SAWebServiceOld.ListMediaCutsInfoSession request) {
            return base.Channel.ListMediaCutsInfo(request);
        }
        
        public System.Data.DataSet ListMediaCutsInfo(string strSessionID, BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            BVWebServiceTestProject.SAWebServiceOld.ListMediaCutsInfoSession inValue = new BVWebServiceTestProject.SAWebServiceOld.ListMediaCutsInfoSession();
            inValue.strSessionID = strSessionID;
            inValue.searchCriteria = searchCriteria;
            inValue.nMaxRow = nMaxRow;
            BVWebServiceTestProject.SAWebServiceOld.ListMediaCutsInfoSession1 retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).ListMediaCutsInfo(inValue);
            return retVal.ListMediaCutsInfoSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.GetDetailedAirDateSession1 BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.GetDetailedAirDate(BVWebServiceTestProject.SAWebServiceOld.GetDetailedAirDateSession request) {
            return base.Channel.GetDetailedAirDate(request);
        }
        
        public System.Data.DataSet GetDetailedAirDate(string strSessionID, int nMediaInventoryId) {
            BVWebServiceTestProject.SAWebServiceOld.GetDetailedAirDateSession inValue = new BVWebServiceTestProject.SAWebServiceOld.GetDetailedAirDateSession();
            inValue.strSessionID = strSessionID;
            inValue.nMediaInventoryId = nMediaInventoryId;
            BVWebServiceTestProject.SAWebServiceOld.GetDetailedAirDateSession1 retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).GetDetailedAirDate(inValue);
            return retVal.GetDetailedAirDateSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.ListPackageCutsInfoSession1 BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.ListPackageCutsInfo(BVWebServiceTestProject.SAWebServiceOld.ListPackageCutsInfoSession request) {
            return base.Channel.ListPackageCutsInfo(request);
        }
        
        public System.Data.DataSet ListPackageCutsInfo(string strSessionID, BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            BVWebServiceTestProject.SAWebServiceOld.ListPackageCutsInfoSession inValue = new BVWebServiceTestProject.SAWebServiceOld.ListPackageCutsInfoSession();
            inValue.strSessionID = strSessionID;
            inValue.searchCriteria = searchCriteria;
            inValue.nMaxRow = nMaxRow;
            BVWebServiceTestProject.SAWebServiceOld.ListPackageCutsInfoSession1 retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).ListPackageCutsInfo(inValue);
            return retVal.ListPackageCutsInfoSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.ListPackageMediaInfoSession1 BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.ListPackageMediaInfo(BVWebServiceTestProject.SAWebServiceOld.ListPackageMediaInfoSession request) {
            return base.Channel.ListPackageMediaInfo(request);
        }
        
        public System.Data.DataSet ListPackageMediaInfo(string strSessionID, BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            BVWebServiceTestProject.SAWebServiceOld.ListPackageMediaInfoSession inValue = new BVWebServiceTestProject.SAWebServiceOld.ListPackageMediaInfoSession();
            inValue.strSessionID = strSessionID;
            inValue.searchCriteria = searchCriteria;
            inValue.nMaxRow = nMaxRow;
            BVWebServiceTestProject.SAWebServiceOld.ListPackageMediaInfoSession1 retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).ListPackageMediaInfo(inValue);
            return retVal.ListPackageMediaInfoSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.SearchMediaAirDateSession1 BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.SearchMediaAirDate(BVWebServiceTestProject.SAWebServiceOld.SearchMediaAirDateSession request) {
            return base.Channel.SearchMediaAirDate(request);
        }
        
        public string SearchMediaAirDate(string strSessionID, string strMediaHouseNumber, int nTune_value) {
            BVWebServiceTestProject.SAWebServiceOld.SearchMediaAirDateSession inValue = new BVWebServiceTestProject.SAWebServiceOld.SearchMediaAirDateSession();
            inValue.strSessionID = strSessionID;
            inValue.strMediaHouseNumber = strMediaHouseNumber;
            inValue.nTune_value = nTune_value;
            BVWebServiceTestProject.SAWebServiceOld.SearchMediaAirDateSession1 retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).SearchMediaAirDate(inValue);
            return retVal.SearchMediaAirDateSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.SearchPackageAirDateSession1 BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.SearchPackageAirDate(BVWebServiceTestProject.SAWebServiceOld.SearchPackageAirDateSession request) {
            return base.Channel.SearchPackageAirDate(request);
        }
        
        public string SearchPackageAirDate(string strSessionID, string strPackageNumber, int nTune_value) {
            BVWebServiceTestProject.SAWebServiceOld.SearchPackageAirDateSession inValue = new BVWebServiceTestProject.SAWebServiceOld.SearchPackageAirDateSession();
            inValue.strSessionID = strSessionID;
            inValue.strPackageNumber = strPackageNumber;
            inValue.nTune_value = nTune_value;
            BVWebServiceTestProject.SAWebServiceOld.SearchPackageAirDateSession1 retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).SearchPackageAirDate(inValue);
            return retVal.SearchPackageAirDateSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.SearchMediaInfoSession1 BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.SearchMediaInfo(BVWebServiceTestProject.SAWebServiceOld.SearchMediaInfoSession request) {
            return base.Channel.SearchMediaInfo(request);
        }
        
        public System.Data.DataSet SearchMediaInfo(string strSessionID, BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            BVWebServiceTestProject.SAWebServiceOld.SearchMediaInfoSession inValue = new BVWebServiceTestProject.SAWebServiceOld.SearchMediaInfoSession();
            inValue.strSessionID = strSessionID;
            inValue.searchCriteria = searchCriteria;
            inValue.nMaxRow = nMaxRow;
            BVWebServiceTestProject.SAWebServiceOld.SearchMediaInfoSession1 retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).SearchMediaInfo(inValue);
            return retVal.SearchMediaInfoSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.SearchPackageInfoSession1 BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.SearchPackageInfo(BVWebServiceTestProject.SAWebServiceOld.SearchPackageInfoSession request) {
            return base.Channel.SearchPackageInfo(request);
        }
        
        public System.Data.DataSet SearchPackageInfo(string strSessionID, BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            BVWebServiceTestProject.SAWebServiceOld.SearchPackageInfoSession inValue = new BVWebServiceTestProject.SAWebServiceOld.SearchPackageInfoSession();
            inValue.strSessionID = strSessionID;
            inValue.searchCriteria = searchCriteria;
            inValue.nMaxRow = nMaxRow;
            BVWebServiceTestProject.SAWebServiceOld.SearchPackageInfoSession1 retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).SearchPackageInfo(inValue);
            return retVal.SearchPackageInfoSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.ListMediaCutsInfoResponse BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.ListMediaCutsInfo1(BVWebServiceTestProject.SAWebServiceOld.ListMediaCutsInfoRequest request) {
            return base.Channel.ListMediaCutsInfo1(request);
        }
        
        public System.Data.DataSet ListMediaCutsInfo1(BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            BVWebServiceTestProject.SAWebServiceOld.ListMediaCutsInfoRequest inValue = new BVWebServiceTestProject.SAWebServiceOld.ListMediaCutsInfoRequest();
            inValue.searchCriteria = searchCriteria;
            inValue.nMaxRow = nMaxRow;
            BVWebServiceTestProject.SAWebServiceOld.ListMediaCutsInfoResponse retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).ListMediaCutsInfo1(inValue);
            return retVal.ListMediaCutsInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.GetDetailedAirDateResponse BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.GetDetailedAirDate1(BVWebServiceTestProject.SAWebServiceOld.GetDetailedAirDateRequest request) {
            return base.Channel.GetDetailedAirDate1(request);
        }
        
        public System.Data.DataSet GetDetailedAirDate1(int nMediaInventoryId) {
            BVWebServiceTestProject.SAWebServiceOld.GetDetailedAirDateRequest inValue = new BVWebServiceTestProject.SAWebServiceOld.GetDetailedAirDateRequest();
            inValue.nMediaInventoryId = nMediaInventoryId;
            BVWebServiceTestProject.SAWebServiceOld.GetDetailedAirDateResponse retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).GetDetailedAirDate1(inValue);
            return retVal.GetDetailedAirDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.ListPackageCutsInfoResponse BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.ListPackageCutsInfo1(BVWebServiceTestProject.SAWebServiceOld.ListPackageCutsInfoRequest request) {
            return base.Channel.ListPackageCutsInfo1(request);
        }
        
        public System.Data.DataSet ListPackageCutsInfo1(BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            BVWebServiceTestProject.SAWebServiceOld.ListPackageCutsInfoRequest inValue = new BVWebServiceTestProject.SAWebServiceOld.ListPackageCutsInfoRequest();
            inValue.searchCriteria = searchCriteria;
            inValue.nMaxRow = nMaxRow;
            BVWebServiceTestProject.SAWebServiceOld.ListPackageCutsInfoResponse retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).ListPackageCutsInfo1(inValue);
            return retVal.ListPackageCutsInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.ListPackageMediaInfoResponse BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.ListPackageMediaInfo1(BVWebServiceTestProject.SAWebServiceOld.ListPackageMediaInfoRequest request) {
            return base.Channel.ListPackageMediaInfo1(request);
        }
        
        public System.Data.DataSet ListPackageMediaInfo1(BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            BVWebServiceTestProject.SAWebServiceOld.ListPackageMediaInfoRequest inValue = new BVWebServiceTestProject.SAWebServiceOld.ListPackageMediaInfoRequest();
            inValue.searchCriteria = searchCriteria;
            inValue.nMaxRow = nMaxRow;
            BVWebServiceTestProject.SAWebServiceOld.ListPackageMediaInfoResponse retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).ListPackageMediaInfo1(inValue);
            return retVal.ListPackageMediaInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.SearchMediaAirDateResponse BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.SearchMediaAirDate1(BVWebServiceTestProject.SAWebServiceOld.SearchMediaAirDateRequest request) {
            return base.Channel.SearchMediaAirDate1(request);
        }
        
        public string SearchMediaAirDate1(string strMediaHouseNumber, int nTune_value) {
            BVWebServiceTestProject.SAWebServiceOld.SearchMediaAirDateRequest inValue = new BVWebServiceTestProject.SAWebServiceOld.SearchMediaAirDateRequest();
            inValue.strMediaHouseNumber = strMediaHouseNumber;
            inValue.nTune_value = nTune_value;
            BVWebServiceTestProject.SAWebServiceOld.SearchMediaAirDateResponse retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).SearchMediaAirDate1(inValue);
            return retVal.SearchMediaAirDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.SearchPackageAirDateResponse BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.SearchPackageAirDate1(BVWebServiceTestProject.SAWebServiceOld.SearchPackageAirDateRequest request) {
            return base.Channel.SearchPackageAirDate1(request);
        }
        
        public string SearchPackageAirDate1(string strPackageNumber, int nTune_value) {
            BVWebServiceTestProject.SAWebServiceOld.SearchPackageAirDateRequest inValue = new BVWebServiceTestProject.SAWebServiceOld.SearchPackageAirDateRequest();
            inValue.strPackageNumber = strPackageNumber;
            inValue.nTune_value = nTune_value;
            BVWebServiceTestProject.SAWebServiceOld.SearchPackageAirDateResponse retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).SearchPackageAirDate1(inValue);
            return retVal.SearchPackageAirDateResult;
        }
        
        public string SearchFeatureAirDate(int intFeatureMediaInventoryID, int nTune_value) {
            return base.Channel.SearchFeatureAirDate(intFeatureMediaInventoryID, nTune_value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.SearchMediaInfoResponse BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.SearchMediaInfo1(BVWebServiceTestProject.SAWebServiceOld.SearchMediaInfoRequest request) {
            return base.Channel.SearchMediaInfo1(request);
        }
        
        public System.Data.DataSet SearchMediaInfo1(BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            BVWebServiceTestProject.SAWebServiceOld.SearchMediaInfoRequest inValue = new BVWebServiceTestProject.SAWebServiceOld.SearchMediaInfoRequest();
            inValue.searchCriteria = searchCriteria;
            inValue.nMaxRow = nMaxRow;
            BVWebServiceTestProject.SAWebServiceOld.SearchMediaInfoResponse retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).SearchMediaInfo1(inValue);
            return retVal.SearchMediaInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.SAWebServiceOld.SearchPackageInfoResponse BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap.SearchPackageInfo1(BVWebServiceTestProject.SAWebServiceOld.SearchPackageInfoRequest request) {
            return base.Channel.SearchPackageInfo1(request);
        }
        
        public System.Data.DataSet SearchPackageInfo1(BVWebServiceTestProject.SAWebServiceOld.SearchCriterion[] searchCriteria, int nMaxRow) {
            BVWebServiceTestProject.SAWebServiceOld.SearchPackageInfoRequest inValue = new BVWebServiceTestProject.SAWebServiceOld.SearchPackageInfoRequest();
            inValue.searchCriteria = searchCriteria;
            inValue.nMaxRow = nMaxRow;
            BVWebServiceTestProject.SAWebServiceOld.SearchPackageInfoResponse retVal = ((BVWebServiceTestProject.SAWebServiceOld.SAWebServiceSoap)(this)).SearchPackageInfo1(inValue);
            return retVal.SearchPackageInfoResult;
        }
    }
}
