//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVWebServiceTestProject.BVWebServiceOld {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pbswebservice.broadviewsoftware.com/BVWebService", ConfigurationName="BVWebServiceOld.BVWebServiceSoap")]
    public interface BVWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetDeal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDeal(out string strLockID, string strSessionID, int nDealID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutDeal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void PutDeal(string strSessionID, int nDealID, string strLockID, System.Data.DataSet dsDeal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetDealAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDealAll(out string strLockID, string strSessionID, int nDealID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetDealWithFunding", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDealWithFunding(out string strLockID, string strSessionID, int nDealID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutDealWithFunding", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void PutDealWithFunding(string strSessionID, int nDealID, string strLockID, System.Data.DataSet dsDeal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetDealWithGeneral", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDealWithGeneral(out string strLockID, string strSessionID, int nDealID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutDealWithGeneral", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void PutDealWithGeneral(string strSessionID, int nDealID, string strLockID, System.Data.DataSet dsDeal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetDealWithRights", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDealWithRights(out string strLockID, string strSessionID, int nDealID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutDealWithRights", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void PutDealWithRights(string strSessionID, int nDealID, string strLockID, System.Data.DataSet dsDeal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetDealWithTechnical", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDealWithTechnical(out string strLockID, string strSessionID, int nDealID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutDealWithTechnical", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void PutDealWithTechnical(string strSessionID, int nDealID, string strLockID, System.Data.DataSet dsDeal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetMasterDeal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMasterDeal(string strSessionID, string strLimitingDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetMediaInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMediaInventory(out string strLockID, string strSessionID, int nMediaInventoryID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutMediaInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void PutMediaInventory(string strSessionID, string strLockID, System.Data.DataSet dsMediaInventory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/CreateMediaInventoryRevis" +
            "ion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void CreateMediaInventoryRevision(string strSessionID, string strLockId, int nOldMediaInventoryID, int nNewMediaInventoryRevisionID);
        
        // CODEGEN: Parameter 'bBarCode' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetBarCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="bBarCode")]
        BVWebServiceTestProject.BVWebServiceOld.GetBarCodeResponse GetBarCode(BVWebServiceTestProject.BVWebServiceOld.GetBarCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/DealSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet DealSearch(string strSessionID, BVWebServiceTestProject.BVWebServiceOld.SearchCriterion[] SearchCriteria, int nMaxRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/ProgramSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet ProgramSearch(string strSessionID, BVWebServiceTestProject.BVWebServiceOld.SearchCriterion[] SearchCriteria, int nMaxRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/MasterDealSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet MasterDealSearch(string strSessionID, BVWebServiceTestProject.BVWebServiceOld.SearchCriterion[] SearchCriteria, int nMaxRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/MediaInventorySearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet MediaInventorySearch(string strSessionID, BVWebServiceTestProject.BVWebServiceOld.SearchCriterion[] SearchCriteria, int nMaxRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/TrafficItemSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet TrafficItemSearch(string strSessionID, BVWebServiceTestProject.BVWebServiceOld.SearchCriterion[] SearchCriteria, int nMaxRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/AdCopySearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet AdCopySearch(string strSessionID, BVWebServiceTestProject.BVWebServiceOld.SearchCriterion[] SearchCriteria, int nMaxRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/ValidateEpisodeSlate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet ValidateEpisodeSlate(string p_sSessionId, string p_sNolaRoot, int p_iStartingEpisodeNumber, int p_iNumberOfPrograms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadBillTo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadBillTo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadBillToContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadBillToContact();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadCaptionVendor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadCaptionVendor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadCompany", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadCompany();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadContactType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadContactType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadDisclaimer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadDisclaimer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadDistributors", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadDistributors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadFunders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadFunders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadFunderType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadFunderType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadGenre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadGenre();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadKeywords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadKeywords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadLanguage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadLanguage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadLocalUnderwriting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadLocalUnderwriting();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadPBSProgramType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadPBSProgramType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadPlayRule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadPlayRule();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadProgramType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadProgramType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadRating", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadRating();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadSchoolRights", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadSchoolRights();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadUplinks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadUplinks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadVersionFormatAndType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadVersionFormatAndType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadAudioType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadAudioType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadTalentRoles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadTalentRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadSurroundSoundType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadSurroundSoundType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadAspectRatioType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadAspectRatioType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadAssetCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadAssetCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadHighDefType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadHighDefType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadVideoFormat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadVideoFormat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadMediaFeatureClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadMediaFeatureClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadCutItemType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadCutItemType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadMediaFormatType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadMediaFormatType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadMediaInventoryType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadMediaInventoryType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadMediaStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadMediaStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadMediaFeature", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadMediaFeature();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadPackageType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadPackageType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadOacPreOfferDescriptio" +
            "nType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadOacPreOfferDescriptionType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadOacPostOfferDescripti" +
            "onType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadOacPostOfferDescriptionType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadVChipValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadVChipValues();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadAlliantContractModels" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadAlliantContractModels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/LoadStations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet LoadStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/CreateProgram", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void CreateProgram(
                    string strSessionID, 
                    int nMasterDealID, 
                    string strMasterDealTitle, 
                    string strSeason, 
                    int nDealID, 
                    string strDealDesc, 
                    string strDealSynopsis, 
                    int nPBSProgramTypeID, 
                    int nUpLinkID, 
                    int[] nProgramIDs, 
                    int nProgramTypeID, 
                    int nDuration, 
                    string strNolaRoot, 
                    int nFirstEpisodeNumber, 
                    int nIncrement, 
                    int nDistributorID, 
                    int nGenreID, 
                    bool bLive, 
                    bool bRecord, 
                    int nDefaultRatingID, 
                    int nDisclaimerID, 
                    string strFirstPictureLockDate, 
                    int nOperatingUnit, 
                    string strOperatingGroup, 
                    BVWebServiceTestProject.BVWebServiceOld.Packages[] cPackages, 
                    int nAssetVChipID, 
                    string sAssetEpisodeTitle, 
                    string sAssetTitleString, 
                    bool p_bIsFinalTitle, 
                    bool p_bSDRightsFlag, 
                    bool p_bHDRightsFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/ListProgramByDeal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet ListProgramByDeal(string strSessionID, int nDealID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/ListProgramPackagesByProg" +
            "ram", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet ListProgramPackagesByProgram(string strSessionID, int nProgramID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/ListDealsByMasterDeal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet ListDealsByMasterDeal(string strSessionID, int nDealID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetProgramDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet GetProgramDetails(out string strLockID, string strSessionID, int nProgramID, bool bLockFlag, bool bGetPremiereDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutProgramDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void PutProgramDetails(string strSessionID, int nProgramID, string strLockID, System.Data.DataSet dsDeal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetTalent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="dEpisodeAppTo")]
        System.Data.DataSet GetTalent(out System.Data.DataSet dEpisodeTalent, out System.Data.DataSet dTalent, string strSessionID, int nDealID, int nTalentID, int nRoleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutTalent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void PutTalent(string strSessionID, System.Data.DataSet dEpisodeTalent, System.Data.DataSet dTalent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/TalentSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet TalentSearch(string strSessionID, string sTalentName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetFormatSheet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet GetFormatSheet(out string strLockID, string strSessionID, int nFormatSheetID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutFormatSheet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void PutFormatSheet(string strSessionID, string strLockID, System.Data.DataSet dsFormatSheet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/DeleteFormatSheet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void DeleteFormatSheet(string strSessionID, int nTabId, string strLockId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetMusicCue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet GetMusicCue(out string strLockID, string strSessionID, int nMusicCueID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutMusicCue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void PutMusicCue(string strSessionID, string strLockID, System.Data.DataSet dsMusicCue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/DeleteMusicCue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void DeleteMusicCue(string strSessionID, int nTabId, string strLockId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetVisualArt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet GetVisualArt(out string strLockID, string strSessionID, int nVisualArtID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutVisualArt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void PutVisualArt(string strSessionID, string strLockID, System.Data.DataSet dsVisualArt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/DeleteVisualArt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void DeleteVisualArt(string strSessionID, int nTabId, string strLockId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetOAC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet GetOAC(out string strLockID, string strSessionID, int nOACID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutOAC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void PutOAC(string strSessionID, string strLockID, System.Data.DataSet dsOAC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/DeleteOAC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void DeleteOAC(string strSessionID, int nTabId, string strLockId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetIWT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet GetIWT(out string strLockID, string strSessionID, int nIWTID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutIWT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void PutIWT(string strSessionID, string strLockID, System.Data.DataSet dsIWT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/DeleteIWT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void DeleteIWT(string strSessionID, int nTabId, string strLockId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetUCC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet GetUCC(out string strLockID, string strSessionID, int nUCCID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutUCC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void PutUCC(string strSessionID, string strLockID, System.Data.DataSet dsUCC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/DeleteUCC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void DeleteUCC(string strSessionID, int nTabId, string strLockId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetAdCopy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet GetAdCopy(out string strLockID, string strSessionID, int nAdCopyId, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutAdCopy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void PutAdCopy(string strSessionID, int nAdCopyId, string strLockID, System.Data.DataSet dsAdCopy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetPackage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet GetPackage(out string strLockID, string strSessionID, int nPackageID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetFeatureMediaInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet GetFeatureMediaInventory(out string strLockID, string strSessionID, int nFeatureMediaInventoryID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutFeatureMediaInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void PutFeatureMediaInventory(string strSessionID, string strLockID, System.Data.DataSet dsFeatureMediaInventory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetMediaInventoryRevision" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet GetMediaInventoryRevision(out string strLockID, string strSessionID, int nMediaInventoryRevisionID, bool bLockFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutMediaInventoryRevision" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void PutMediaInventoryRevision(string strSessionID, string strLockID, System.Data.DataSet dsMediaInventoryRevision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetAssetAppliesToRangeByT" +
            "ab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet GetAssetAppliesToRangeByTab(string strSessionID, int nTabID, string strTabType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutAssetAppliesToRangeByT" +
            "ab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void PutAssetAppliesToRangeByTab(string strSessionID, System.Data.DataSet dsAssetAppliesTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetPackageAppliesToRangeB" +
            "yTab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet GetPackageAppliesToRangeByTab(string strSessionID, int nTabID, string strTabType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/PutPackageAppliesToRangeB" +
            "yTab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void PutPackageAppliesToRangeByTab(string strSessionID, System.Data.DataSet dsPackageAppliesTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/ListTabMapByDeal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet ListTabMapByDeal(string strSessionID, int nDealId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/ListPAADeadline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet ListPAADeadline(string strSessionID, int nDealStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/ListFormDeadline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet ListFormDeadline(string strSessionID, int nDealStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/ListMissingEpisodeFormDea" +
            "dline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet ListMissingEpisodeFormDeadline(string strSessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/ListMissingVersionFormDea" +
            "dline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        System.Data.DataSet ListMissingVersionFormDeadline(string strSessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetDiscrepancyProgram", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sPackageID")]
        string GetDiscrepancyProgram(out string sPackagenumber, out string sPackageTile, out string sProgramTile, out string sSeriesTile, out string sProgramEpisodeTitle, out System.DateTime dSchedDateTime, out int nSchedDuration, string sChannel, string sDicrepancyStartDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/ReleaseLock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void ReleaseLock(string strSessionID, string strLockID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/GetIDs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        int[] GetIDs(int nHowMany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/OpenSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        string OpenSession(BVWebServiceTestProject.BVWebServiceOld.UserProfile userProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/CloseSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void CloseSession(string strSessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pbswebservice.broadviewsoftware.com/BVWebService/DebugTimeOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UserProfileBase))]
        void DebugTimeOut(string strSessionID, int nTimeDelay);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBarCode", WrapperNamespace="http://pbswebservice.broadviewsoftware.com/BVWebService", IsWrapped=true)]
    public partial class GetBarCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pbswebservice.broadviewsoftware.com/BVWebService", Order=0)]
        public string strSessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pbswebservice.broadviewsoftware.com/BVWebService", Order=1)]
        public int nMediaInventoryID;
        
        public GetBarCodeRequest() {
        }
        
        public GetBarCodeRequest(string strSessionID, int nMediaInventoryID) {
            this.strSessionID = strSessionID;
            this.nMediaInventoryID = nMediaInventoryID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBarCodeResponse", WrapperNamespace="http://pbswebservice.broadviewsoftware.com/BVWebService", IsWrapped=true)]
    public partial class GetBarCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pbswebservice.broadviewsoftware.com/BVWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bBarCode;
        
        public GetBarCodeResponse() {
        }
        
        public GetBarCodeResponse(byte[] bBarCode) {
            this.bBarCode = bBarCode;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pbswebservice.broadviewsoftware.com/BVWebService")]
    public partial class SearchCriterion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string searchFieldField;
        
        private string searchValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SearchField {
            get {
                return this.searchFieldField;
            }
            set {
                this.searchFieldField = value;
                this.RaisePropertyChanged("SearchField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SearchValue {
            get {
                return this.searchValueField;
            }
            set {
                this.searchValueField = value;
                this.RaisePropertyChanged("SearchValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserProfile))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pbswebservice.broadviewsoftware.com/BVWebService")]
    public partial class UserProfileBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sConnectIdField;
        
        private string sFirstNameField;
        
        private string sLastNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sConnectId {
            get {
                return this.sConnectIdField;
            }
            set {
                this.sConnectIdField = value;
                this.RaisePropertyChanged("sConnectId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sFirstName {
            get {
                return this.sFirstNameField;
            }
            set {
                this.sFirstNameField = value;
                this.RaisePropertyChanged("sFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sLastName {
            get {
                return this.sLastNameField;
            }
            set {
                this.sLastNameField = value;
                this.RaisePropertyChanged("sLastName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pbswebservice.broadviewsoftware.com/BVWebService")]
    public partial class UserProfile : UserProfileBase {
        
        private string[] oOperatingGroupField;
        
        private short nOperatingUnitField;
        
        private short nUnitTypeField;
        
        private short nRoleField;
        
        private string sExternalEmailField;
        
        private string sPhoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("sCode")]
        public string[] oOperatingGroup {
            get {
                return this.oOperatingGroupField;
            }
            set {
                this.oOperatingGroupField = value;
                this.RaisePropertyChanged("oOperatingGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short nOperatingUnit {
            get {
                return this.nOperatingUnitField;
            }
            set {
                this.nOperatingUnitField = value;
                this.RaisePropertyChanged("nOperatingUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public short nUnitType {
            get {
                return this.nUnitTypeField;
            }
            set {
                this.nUnitTypeField = value;
                this.RaisePropertyChanged("nUnitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public short nRole {
            get {
                return this.nRoleField;
            }
            set {
                this.nRoleField = value;
                this.RaisePropertyChanged("nRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sExternalEmail {
            get {
                return this.sExternalEmailField;
            }
            set {
                this.sExternalEmailField = value;
                this.RaisePropertyChanged("sExternalEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sPhoneNumber {
            get {
                return this.sPhoneNumberField;
            }
            set {
                this.sPhoneNumberField = value;
                this.RaisePropertyChanged("sPhoneNumber");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pbswebservice.broadviewsoftware.com/BVWebService")]
    public partial class Packages : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int formatAndTypeIDField;
        
        private int lengthField;
        
        private int vchipIDField;
        
        private short isVCHIPEmbeddedField;
        
        private short isEiQualifiedField;
        
        private short isEiEmbeddedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FormatAndTypeID {
            get {
                return this.formatAndTypeIDField;
            }
            set {
                this.formatAndTypeIDField = value;
                this.RaisePropertyChanged("FormatAndTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("Length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int VchipID {
            get {
                return this.vchipIDField;
            }
            set {
                this.vchipIDField = value;
                this.RaisePropertyChanged("VchipID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public short IsVCHIPEmbedded {
            get {
                return this.isVCHIPEmbeddedField;
            }
            set {
                this.isVCHIPEmbeddedField = value;
                this.RaisePropertyChanged("IsVCHIPEmbedded");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public short IsEiQualified {
            get {
                return this.isEiQualifiedField;
            }
            set {
                this.isEiQualifiedField = value;
                this.RaisePropertyChanged("IsEiQualified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public short IsEiEmbedded {
            get {
                return this.isEiEmbeddedField;
            }
            set {
                this.isEiEmbeddedField = value;
                this.RaisePropertyChanged("IsEiEmbedded");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BVWebServiceSoapChannel : BVWebServiceTestProject.BVWebServiceOld.BVWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BVWebServiceSoapClient : System.ServiceModel.ClientBase<BVWebServiceTestProject.BVWebServiceOld.BVWebServiceSoap>, BVWebServiceTestProject.BVWebServiceOld.BVWebServiceSoap {
        
        public BVWebServiceSoapClient() {
        }
        
        public BVWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BVWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BVWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BVWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetDeal(out string strLockID, string strSessionID, int nDealID, bool bLockFlag) {
            return base.Channel.GetDeal(out strLockID, strSessionID, nDealID, bLockFlag);
        }
        
        public void PutDeal(string strSessionID, int nDealID, string strLockID, System.Data.DataSet dsDeal) {
            base.Channel.PutDeal(strSessionID, nDealID, strLockID, dsDeal);
        }
        
        public System.Data.DataSet GetDealAll(out string strLockID, string strSessionID, int nDealID, bool bLockFlag) {
            return base.Channel.GetDealAll(out strLockID, strSessionID, nDealID, bLockFlag);
        }
        
        public System.Data.DataSet GetDealWithFunding(out string strLockID, string strSessionID, int nDealID, bool bLockFlag) {
            return base.Channel.GetDealWithFunding(out strLockID, strSessionID, nDealID, bLockFlag);
        }
        
        public void PutDealWithFunding(string strSessionID, int nDealID, string strLockID, System.Data.DataSet dsDeal) {
            base.Channel.PutDealWithFunding(strSessionID, nDealID, strLockID, dsDeal);
        }
        
        public System.Data.DataSet GetDealWithGeneral(out string strLockID, string strSessionID, int nDealID, bool bLockFlag) {
            return base.Channel.GetDealWithGeneral(out strLockID, strSessionID, nDealID, bLockFlag);
        }
        
        public void PutDealWithGeneral(string strSessionID, int nDealID, string strLockID, System.Data.DataSet dsDeal) {
            base.Channel.PutDealWithGeneral(strSessionID, nDealID, strLockID, dsDeal);
        }
        
        public System.Data.DataSet GetDealWithRights(out string strLockID, string strSessionID, int nDealID, bool bLockFlag) {
            return base.Channel.GetDealWithRights(out strLockID, strSessionID, nDealID, bLockFlag);
        }
        
        public void PutDealWithRights(string strSessionID, int nDealID, string strLockID, System.Data.DataSet dsDeal) {
            base.Channel.PutDealWithRights(strSessionID, nDealID, strLockID, dsDeal);
        }
        
        public System.Data.DataSet GetDealWithTechnical(out string strLockID, string strSessionID, int nDealID, bool bLockFlag) {
            return base.Channel.GetDealWithTechnical(out strLockID, strSessionID, nDealID, bLockFlag);
        }
        
        public void PutDealWithTechnical(string strSessionID, int nDealID, string strLockID, System.Data.DataSet dsDeal) {
            base.Channel.PutDealWithTechnical(strSessionID, nDealID, strLockID, dsDeal);
        }
        
        public System.Data.DataSet GetMasterDeal(string strSessionID, string strLimitingDate) {
            return base.Channel.GetMasterDeal(strSessionID, strLimitingDate);
        }
        
        public System.Data.DataSet GetMediaInventory(out string strLockID, string strSessionID, int nMediaInventoryID, bool bLockFlag) {
            return base.Channel.GetMediaInventory(out strLockID, strSessionID, nMediaInventoryID, bLockFlag);
        }
        
        public void PutMediaInventory(string strSessionID, string strLockID, System.Data.DataSet dsMediaInventory) {
            base.Channel.PutMediaInventory(strSessionID, strLockID, dsMediaInventory);
        }
        
        public void CreateMediaInventoryRevision(string strSessionID, string strLockId, int nOldMediaInventoryID, int nNewMediaInventoryRevisionID) {
            base.Channel.CreateMediaInventoryRevision(strSessionID, strLockId, nOldMediaInventoryID, nNewMediaInventoryRevisionID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVWebServiceTestProject.BVWebServiceOld.GetBarCodeResponse BVWebServiceTestProject.BVWebServiceOld.BVWebServiceSoap.GetBarCode(BVWebServiceTestProject.BVWebServiceOld.GetBarCodeRequest request) {
            return base.Channel.GetBarCode(request);
        }
        
        public byte[] GetBarCode(string strSessionID, int nMediaInventoryID) {
            BVWebServiceTestProject.BVWebServiceOld.GetBarCodeRequest inValue = new BVWebServiceTestProject.BVWebServiceOld.GetBarCodeRequest();
            inValue.strSessionID = strSessionID;
            inValue.nMediaInventoryID = nMediaInventoryID;
            BVWebServiceTestProject.BVWebServiceOld.GetBarCodeResponse retVal = ((BVWebServiceTestProject.BVWebServiceOld.BVWebServiceSoap)(this)).GetBarCode(inValue);
            return retVal.bBarCode;
        }
        
        public System.Data.DataSet DealSearch(string strSessionID, BVWebServiceTestProject.BVWebServiceOld.SearchCriterion[] SearchCriteria, int nMaxRows) {
            return base.Channel.DealSearch(strSessionID, SearchCriteria, nMaxRows);
        }
        
        public System.Data.DataSet ProgramSearch(string strSessionID, BVWebServiceTestProject.BVWebServiceOld.SearchCriterion[] SearchCriteria, int nMaxRows) {
            return base.Channel.ProgramSearch(strSessionID, SearchCriteria, nMaxRows);
        }
        
        public System.Data.DataSet MasterDealSearch(string strSessionID, BVWebServiceTestProject.BVWebServiceOld.SearchCriterion[] SearchCriteria, int nMaxRows) {
            return base.Channel.MasterDealSearch(strSessionID, SearchCriteria, nMaxRows);
        }
        
        public System.Data.DataSet MediaInventorySearch(string strSessionID, BVWebServiceTestProject.BVWebServiceOld.SearchCriterion[] SearchCriteria, int nMaxRows) {
            return base.Channel.MediaInventorySearch(strSessionID, SearchCriteria, nMaxRows);
        }
        
        public System.Data.DataSet TrafficItemSearch(string strSessionID, BVWebServiceTestProject.BVWebServiceOld.SearchCriterion[] SearchCriteria, int nMaxRows) {
            return base.Channel.TrafficItemSearch(strSessionID, SearchCriteria, nMaxRows);
        }
        
        public System.Data.DataSet AdCopySearch(string strSessionID, BVWebServiceTestProject.BVWebServiceOld.SearchCriterion[] SearchCriteria, int nMaxRows) {
            return base.Channel.AdCopySearch(strSessionID, SearchCriteria, nMaxRows);
        }
        
        public System.Data.DataSet ValidateEpisodeSlate(string p_sSessionId, string p_sNolaRoot, int p_iStartingEpisodeNumber, int p_iNumberOfPrograms) {
            return base.Channel.ValidateEpisodeSlate(p_sSessionId, p_sNolaRoot, p_iStartingEpisodeNumber, p_iNumberOfPrograms);
        }
        
        public System.Data.DataSet LoadBillTo() {
            return base.Channel.LoadBillTo();
        }
        
        public System.Data.DataSet LoadBillToContact() {
            return base.Channel.LoadBillToContact();
        }
        
        public System.Data.DataSet LoadCaptionVendor() {
            return base.Channel.LoadCaptionVendor();
        }
        
        public System.Data.DataSet LoadCompany() {
            return base.Channel.LoadCompany();
        }
        
        public System.Data.DataSet LoadContactType() {
            return base.Channel.LoadContactType();
        }
        
        public System.Data.DataSet LoadDisclaimer() {
            return base.Channel.LoadDisclaimer();
        }
        
        public System.Data.DataSet LoadDistributors() {
            return base.Channel.LoadDistributors();
        }
        
        public System.Data.DataSet LoadFunders() {
            return base.Channel.LoadFunders();
        }
        
        public System.Data.DataSet LoadFunderType() {
            return base.Channel.LoadFunderType();
        }
        
        public System.Data.DataSet LoadGenre() {
            return base.Channel.LoadGenre();
        }
        
        public System.Data.DataSet LoadKeywords() {
            return base.Channel.LoadKeywords();
        }
        
        public System.Data.DataSet LoadLanguage() {
            return base.Channel.LoadLanguage();
        }
        
        public System.Data.DataSet LoadLocalUnderwriting() {
            return base.Channel.LoadLocalUnderwriting();
        }
        
        public System.Data.DataSet LoadPBSProgramType() {
            return base.Channel.LoadPBSProgramType();
        }
        
        public System.Data.DataSet LoadPlayRule() {
            return base.Channel.LoadPlayRule();
        }
        
        public System.Data.DataSet LoadProgramType() {
            return base.Channel.LoadProgramType();
        }
        
        public System.Data.DataSet LoadRating() {
            return base.Channel.LoadRating();
        }
        
        public System.Data.DataSet LoadSchoolRights() {
            return base.Channel.LoadSchoolRights();
        }
        
        public System.Data.DataSet LoadUplinks() {
            return base.Channel.LoadUplinks();
        }
        
        public System.Data.DataSet LoadVersionFormatAndType() {
            return base.Channel.LoadVersionFormatAndType();
        }
        
        public System.Data.DataSet LoadAudioType() {
            return base.Channel.LoadAudioType();
        }
        
        public System.Data.DataSet LoadTalentRoles() {
            return base.Channel.LoadTalentRoles();
        }
        
        public System.Data.DataSet LoadSurroundSoundType() {
            return base.Channel.LoadSurroundSoundType();
        }
        
        public System.Data.DataSet LoadAspectRatioType() {
            return base.Channel.LoadAspectRatioType();
        }
        
        public System.Data.DataSet LoadAssetCategory() {
            return base.Channel.LoadAssetCategory();
        }
        
        public System.Data.DataSet LoadHighDefType() {
            return base.Channel.LoadHighDefType();
        }
        
        public System.Data.DataSet LoadVideoFormat() {
            return base.Channel.LoadVideoFormat();
        }
        
        public System.Data.DataSet LoadMediaFeatureClass() {
            return base.Channel.LoadMediaFeatureClass();
        }
        
        public System.Data.DataSet LoadCutItemType() {
            return base.Channel.LoadCutItemType();
        }
        
        public System.Data.DataSet LoadMediaFormatType() {
            return base.Channel.LoadMediaFormatType();
        }
        
        public System.Data.DataSet LoadMediaInventoryType() {
            return base.Channel.LoadMediaInventoryType();
        }
        
        public System.Data.DataSet LoadMediaStatus() {
            return base.Channel.LoadMediaStatus();
        }
        
        public System.Data.DataSet LoadMediaFeature() {
            return base.Channel.LoadMediaFeature();
        }
        
        public System.Data.DataSet LoadPackageType() {
            return base.Channel.LoadPackageType();
        }
        
        public System.Data.DataSet LoadOacPreOfferDescriptionType() {
            return base.Channel.LoadOacPreOfferDescriptionType();
        }
        
        public System.Data.DataSet LoadOacPostOfferDescriptionType() {
            return base.Channel.LoadOacPostOfferDescriptionType();
        }
        
        public System.Data.DataSet LoadVChipValues() {
            return base.Channel.LoadVChipValues();
        }
        
        public System.Data.DataSet LoadAlliantContractModels() {
            return base.Channel.LoadAlliantContractModels();
        }
        
        public System.Data.DataSet LoadStations() {
            return base.Channel.LoadStations();
        }
        
        public void CreateProgram(
                    string strSessionID, 
                    int nMasterDealID, 
                    string strMasterDealTitle, 
                    string strSeason, 
                    int nDealID, 
                    string strDealDesc, 
                    string strDealSynopsis, 
                    int nPBSProgramTypeID, 
                    int nUpLinkID, 
                    int[] nProgramIDs, 
                    int nProgramTypeID, 
                    int nDuration, 
                    string strNolaRoot, 
                    int nFirstEpisodeNumber, 
                    int nIncrement, 
                    int nDistributorID, 
                    int nGenreID, 
                    bool bLive, 
                    bool bRecord, 
                    int nDefaultRatingID, 
                    int nDisclaimerID, 
                    string strFirstPictureLockDate, 
                    int nOperatingUnit, 
                    string strOperatingGroup, 
                    BVWebServiceTestProject.BVWebServiceOld.Packages[] cPackages, 
                    int nAssetVChipID, 
                    string sAssetEpisodeTitle, 
                    string sAssetTitleString, 
                    bool p_bIsFinalTitle, 
                    bool p_bSDRightsFlag, 
                    bool p_bHDRightsFlag) {
            base.Channel.CreateProgram(strSessionID, nMasterDealID, strMasterDealTitle, strSeason, nDealID, strDealDesc, strDealSynopsis, nPBSProgramTypeID, nUpLinkID, nProgramIDs, nProgramTypeID, nDuration, strNolaRoot, nFirstEpisodeNumber, nIncrement, nDistributorID, nGenreID, bLive, bRecord, nDefaultRatingID, nDisclaimerID, strFirstPictureLockDate, nOperatingUnit, strOperatingGroup, cPackages, nAssetVChipID, sAssetEpisodeTitle, sAssetTitleString, p_bIsFinalTitle, p_bSDRightsFlag, p_bHDRightsFlag);
        }
        
        public System.Data.DataSet ListProgramByDeal(string strSessionID, int nDealID) {
            return base.Channel.ListProgramByDeal(strSessionID, nDealID);
        }
        
        public System.Data.DataSet ListProgramPackagesByProgram(string strSessionID, int nProgramID) {
            return base.Channel.ListProgramPackagesByProgram(strSessionID, nProgramID);
        }
        
        public System.Data.DataSet ListDealsByMasterDeal(string strSessionID, int nDealID) {
            return base.Channel.ListDealsByMasterDeal(strSessionID, nDealID);
        }
        
        public System.Data.DataSet GetProgramDetails(out string strLockID, string strSessionID, int nProgramID, bool bLockFlag, bool bGetPremiereDate) {
            return base.Channel.GetProgramDetails(out strLockID, strSessionID, nProgramID, bLockFlag, bGetPremiereDate);
        }
        
        public void PutProgramDetails(string strSessionID, int nProgramID, string strLockID, System.Data.DataSet dsDeal) {
            base.Channel.PutProgramDetails(strSessionID, nProgramID, strLockID, dsDeal);
        }
        
        public System.Data.DataSet GetTalent(out System.Data.DataSet dEpisodeTalent, out System.Data.DataSet dTalent, string strSessionID, int nDealID, int nTalentID, int nRoleID) {
            return base.Channel.GetTalent(out dEpisodeTalent, out dTalent, strSessionID, nDealID, nTalentID, nRoleID);
        }
        
        public void PutTalent(string strSessionID, System.Data.DataSet dEpisodeTalent, System.Data.DataSet dTalent) {
            base.Channel.PutTalent(strSessionID, dEpisodeTalent, dTalent);
        }
        
        public System.Data.DataSet TalentSearch(string strSessionID, string sTalentName) {
            return base.Channel.TalentSearch(strSessionID, sTalentName);
        }
        
        public System.Data.DataSet GetFormatSheet(out string strLockID, string strSessionID, int nFormatSheetID, bool bLockFlag) {
            return base.Channel.GetFormatSheet(out strLockID, strSessionID, nFormatSheetID, bLockFlag);
        }
        
        public void PutFormatSheet(string strSessionID, string strLockID, System.Data.DataSet dsFormatSheet) {
            base.Channel.PutFormatSheet(strSessionID, strLockID, dsFormatSheet);
        }
        
        public void DeleteFormatSheet(string strSessionID, int nTabId, string strLockId) {
            base.Channel.DeleteFormatSheet(strSessionID, nTabId, strLockId);
        }
        
        public System.Data.DataSet GetMusicCue(out string strLockID, string strSessionID, int nMusicCueID, bool bLockFlag) {
            return base.Channel.GetMusicCue(out strLockID, strSessionID, nMusicCueID, bLockFlag);
        }
        
        public void PutMusicCue(string strSessionID, string strLockID, System.Data.DataSet dsMusicCue) {
            base.Channel.PutMusicCue(strSessionID, strLockID, dsMusicCue);
        }
        
        public void DeleteMusicCue(string strSessionID, int nTabId, string strLockId) {
            base.Channel.DeleteMusicCue(strSessionID, nTabId, strLockId);
        }
        
        public System.Data.DataSet GetVisualArt(out string strLockID, string strSessionID, int nVisualArtID, bool bLockFlag) {
            return base.Channel.GetVisualArt(out strLockID, strSessionID, nVisualArtID, bLockFlag);
        }
        
        public void PutVisualArt(string strSessionID, string strLockID, System.Data.DataSet dsVisualArt) {
            base.Channel.PutVisualArt(strSessionID, strLockID, dsVisualArt);
        }
        
        public void DeleteVisualArt(string strSessionID, int nTabId, string strLockId) {
            base.Channel.DeleteVisualArt(strSessionID, nTabId, strLockId);
        }
        
        public System.Data.DataSet GetOAC(out string strLockID, string strSessionID, int nOACID, bool bLockFlag) {
            return base.Channel.GetOAC(out strLockID, strSessionID, nOACID, bLockFlag);
        }
        
        public void PutOAC(string strSessionID, string strLockID, System.Data.DataSet dsOAC) {
            base.Channel.PutOAC(strSessionID, strLockID, dsOAC);
        }
        
        public void DeleteOAC(string strSessionID, int nTabId, string strLockId) {
            base.Channel.DeleteOAC(strSessionID, nTabId, strLockId);
        }
        
        public System.Data.DataSet GetIWT(out string strLockID, string strSessionID, int nIWTID, bool bLockFlag) {
            return base.Channel.GetIWT(out strLockID, strSessionID, nIWTID, bLockFlag);
        }
        
        public void PutIWT(string strSessionID, string strLockID, System.Data.DataSet dsIWT) {
            base.Channel.PutIWT(strSessionID, strLockID, dsIWT);
        }
        
        public void DeleteIWT(string strSessionID, int nTabId, string strLockId) {
            base.Channel.DeleteIWT(strSessionID, nTabId, strLockId);
        }
        
        public System.Data.DataSet GetUCC(out string strLockID, string strSessionID, int nUCCID, bool bLockFlag) {
            return base.Channel.GetUCC(out strLockID, strSessionID, nUCCID, bLockFlag);
        }
        
        public void PutUCC(string strSessionID, string strLockID, System.Data.DataSet dsUCC) {
            base.Channel.PutUCC(strSessionID, strLockID, dsUCC);
        }
        
        public void DeleteUCC(string strSessionID, int nTabId, string strLockId) {
            base.Channel.DeleteUCC(strSessionID, nTabId, strLockId);
        }
        
        public System.Data.DataSet GetAdCopy(out string strLockID, string strSessionID, int nAdCopyId, bool bLockFlag) {
            return base.Channel.GetAdCopy(out strLockID, strSessionID, nAdCopyId, bLockFlag);
        }
        
        public void PutAdCopy(string strSessionID, int nAdCopyId, string strLockID, System.Data.DataSet dsAdCopy) {
            base.Channel.PutAdCopy(strSessionID, nAdCopyId, strLockID, dsAdCopy);
        }
        
        public System.Data.DataSet GetPackage(out string strLockID, string strSessionID, int nPackageID, bool bLockFlag) {
            return base.Channel.GetPackage(out strLockID, strSessionID, nPackageID, bLockFlag);
        }
        
        public System.Data.DataSet GetFeatureMediaInventory(out string strLockID, string strSessionID, int nFeatureMediaInventoryID, bool bLockFlag) {
            return base.Channel.GetFeatureMediaInventory(out strLockID, strSessionID, nFeatureMediaInventoryID, bLockFlag);
        }
        
        public void PutFeatureMediaInventory(string strSessionID, string strLockID, System.Data.DataSet dsFeatureMediaInventory) {
            base.Channel.PutFeatureMediaInventory(strSessionID, strLockID, dsFeatureMediaInventory);
        }
        
        public System.Data.DataSet GetMediaInventoryRevision(out string strLockID, string strSessionID, int nMediaInventoryRevisionID, bool bLockFlag) {
            return base.Channel.GetMediaInventoryRevision(out strLockID, strSessionID, nMediaInventoryRevisionID, bLockFlag);
        }
        
        public void PutMediaInventoryRevision(string strSessionID, string strLockID, System.Data.DataSet dsMediaInventoryRevision) {
            base.Channel.PutMediaInventoryRevision(strSessionID, strLockID, dsMediaInventoryRevision);
        }
        
        public System.Data.DataSet GetAssetAppliesToRangeByTab(string strSessionID, int nTabID, string strTabType) {
            return base.Channel.GetAssetAppliesToRangeByTab(strSessionID, nTabID, strTabType);
        }
        
        public void PutAssetAppliesToRangeByTab(string strSessionID, System.Data.DataSet dsAssetAppliesTo) {
            base.Channel.PutAssetAppliesToRangeByTab(strSessionID, dsAssetAppliesTo);
        }
        
        public System.Data.DataSet GetPackageAppliesToRangeByTab(string strSessionID, int nTabID, string strTabType) {
            return base.Channel.GetPackageAppliesToRangeByTab(strSessionID, nTabID, strTabType);
        }
        
        public void PutPackageAppliesToRangeByTab(string strSessionID, System.Data.DataSet dsPackageAppliesTo) {
            base.Channel.PutPackageAppliesToRangeByTab(strSessionID, dsPackageAppliesTo);
        }
        
        public System.Data.DataSet ListTabMapByDeal(string strSessionID, int nDealId) {
            return base.Channel.ListTabMapByDeal(strSessionID, nDealId);
        }
        
        public System.Data.DataSet ListPAADeadline(string strSessionID, int nDealStatus) {
            return base.Channel.ListPAADeadline(strSessionID, nDealStatus);
        }
        
        public System.Data.DataSet ListFormDeadline(string strSessionID, int nDealStatus) {
            return base.Channel.ListFormDeadline(strSessionID, nDealStatus);
        }
        
        public System.Data.DataSet ListMissingEpisodeFormDeadline(string strSessionID) {
            return base.Channel.ListMissingEpisodeFormDeadline(strSessionID);
        }
        
        public System.Data.DataSet ListMissingVersionFormDeadline(string strSessionID) {
            return base.Channel.ListMissingVersionFormDeadline(strSessionID);
        }
        
        public string GetDiscrepancyProgram(out string sPackagenumber, out string sPackageTile, out string sProgramTile, out string sSeriesTile, out string sProgramEpisodeTitle, out System.DateTime dSchedDateTime, out int nSchedDuration, string sChannel, string sDicrepancyStartDate) {
            return base.Channel.GetDiscrepancyProgram(out sPackagenumber, out sPackageTile, out sProgramTile, out sSeriesTile, out sProgramEpisodeTitle, out dSchedDateTime, out nSchedDuration, sChannel, sDicrepancyStartDate);
        }
        
        public void ReleaseLock(string strSessionID, string strLockID) {
            base.Channel.ReleaseLock(strSessionID, strLockID);
        }
        
        public int[] GetIDs(int nHowMany) {
            return base.Channel.GetIDs(nHowMany);
        }
        
        public string OpenSession(BVWebServiceTestProject.BVWebServiceOld.UserProfile userProfile) {
            return base.Channel.OpenSession(userProfile);
        }
        
        public void CloseSession(string strSessionID) {
            base.Channel.CloseSession(strSessionID);
        }
        
        public void DebugTimeOut(string strSessionID, int nTimeDelay) {
            base.Channel.DebugTimeOut(strSessionID, nTimeDelay);
        }
    }
}
