//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficDataRightLineMapperWebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterLookupValue
    {
        public int ID { get; set; }
        public Nullable<int> ML_ID { get; set; }
        public string field { get; set; }
        public string BV_Value { get; set; }
        public string RL_Value { get; set; }
    }
}
