//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
// 
#pragma warning disable 1591

namespace TestWebService.SAWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SAWebServiceSoap", Namespace="http://webservices.pbstest.org/SAWebService")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserProfileBase))]
    public partial class SAWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CloseSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback OpenSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListMediaCutsInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDetailedAirDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListPackageCutsInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListPackageMediaInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchMediaAirDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchPackageAirDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchMediaInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchPackageInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListMediaCutsInfo1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDetailedAirDate1OperationCompleted;
        
        private System.Threading.SendOrPostCallback ListPackageCutsInfo1OperationCompleted;
        
        private System.Threading.SendOrPostCallback ListPackageMediaInfo1OperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchMediaAirDate1OperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchPackageAirDate1OperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchFeatureAirDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchMediaInfo1OperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchPackageInfo1OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SAWebService() {
            this.Url = "http://localhost/SAWebService/Service.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CloseSessionCompletedEventHandler CloseSessionCompleted;
        
        /// <remarks/>
        public event OpenSessionCompletedEventHandler OpenSessionCompleted;
        
        /// <remarks/>
        public event ListMediaCutsInfoCompletedEventHandler ListMediaCutsInfoCompleted;
        
        /// <remarks/>
        public event GetDetailedAirDateCompletedEventHandler GetDetailedAirDateCompleted;
        
        /// <remarks/>
        public event ListPackageCutsInfoCompletedEventHandler ListPackageCutsInfoCompleted;
        
        /// <remarks/>
        public event ListPackageMediaInfoCompletedEventHandler ListPackageMediaInfoCompleted;
        
        /// <remarks/>
        public event SearchMediaAirDateCompletedEventHandler SearchMediaAirDateCompleted;
        
        /// <remarks/>
        public event SearchPackageAirDateCompletedEventHandler SearchPackageAirDateCompleted;
        
        /// <remarks/>
        public event SearchMediaInfoCompletedEventHandler SearchMediaInfoCompleted;
        
        /// <remarks/>
        public event SearchPackageInfoCompletedEventHandler SearchPackageInfoCompleted;
        
        /// <remarks/>
        public event ListMediaCutsInfo1CompletedEventHandler ListMediaCutsInfo1Completed;
        
        /// <remarks/>
        public event GetDetailedAirDate1CompletedEventHandler GetDetailedAirDate1Completed;
        
        /// <remarks/>
        public event ListPackageCutsInfo1CompletedEventHandler ListPackageCutsInfo1Completed;
        
        /// <remarks/>
        public event ListPackageMediaInfo1CompletedEventHandler ListPackageMediaInfo1Completed;
        
        /// <remarks/>
        public event SearchMediaAirDate1CompletedEventHandler SearchMediaAirDate1Completed;
        
        /// <remarks/>
        public event SearchPackageAirDate1CompletedEventHandler SearchPackageAirDate1Completed;
        
        /// <remarks/>
        public event SearchFeatureAirDateCompletedEventHandler SearchFeatureAirDateCompleted;
        
        /// <remarks/>
        public event SearchMediaInfo1CompletedEventHandler SearchMediaInfo1Completed;
        
        /// <remarks/>
        public event SearchPackageInfo1CompletedEventHandler SearchPackageInfo1Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/CloseSession", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CloseSession(string strSessionID) {
            this.Invoke("CloseSession", new object[] {
                        strSessionID});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCloseSession(string strSessionID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CloseSession", new object[] {
                        strSessionID}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCloseSession(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void CloseSessionAsync(string strSessionID) {
            this.CloseSessionAsync(strSessionID, null);
        }
        
        /// <remarks/>
        public void CloseSessionAsync(string strSessionID, object userState) {
            if ((this.CloseSessionOperationCompleted == null)) {
                this.CloseSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCloseSessionOperationCompleted);
            }
            this.InvokeAsync("CloseSession", new object[] {
                        strSessionID}, this.CloseSessionOperationCompleted, userState);
        }
        
        private void OnCloseSessionOperationCompleted(object arg) {
            if ((this.CloseSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CloseSessionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/OpenSession", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OpenSession(UserProfile userProfile) {
            object[] results = this.Invoke("OpenSession", new object[] {
                        userProfile});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOpenSession(UserProfile userProfile, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OpenSession", new object[] {
                        userProfile}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndOpenSession(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OpenSessionAsync(UserProfile userProfile) {
            this.OpenSessionAsync(userProfile, null);
        }
        
        /// <remarks/>
        public void OpenSessionAsync(UserProfile userProfile, object userState) {
            if ((this.OpenSessionOperationCompleted == null)) {
                this.OpenSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOpenSessionOperationCompleted);
            }
            this.InvokeAsync("OpenSession", new object[] {
                        userProfile}, this.OpenSessionOperationCompleted, userState);
        }
        
        private void OnOpenSessionOperationCompleted(object arg) {
            if ((this.OpenSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OpenSessionCompleted(this, new OpenSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/ListMediaCutsInfoSession", RequestElementName="ListMediaCutsInfoSession", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="ListMediaCutsInfoSessionResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListMediaCutsInfoSessionResult")]
        public System.Data.DataSet ListMediaCutsInfo(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow) {
            object[] results = this.Invoke("ListMediaCutsInfo", new object[] {
                        strSessionID,
                        searchCriteria,
                        nMaxRow});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListMediaCutsInfo(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListMediaCutsInfo", new object[] {
                        strSessionID,
                        searchCriteria,
                        nMaxRow}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndListMediaCutsInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListMediaCutsInfoAsync(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow) {
            this.ListMediaCutsInfoAsync(strSessionID, searchCriteria, nMaxRow, null);
        }
        
        /// <remarks/>
        public void ListMediaCutsInfoAsync(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow, object userState) {
            if ((this.ListMediaCutsInfoOperationCompleted == null)) {
                this.ListMediaCutsInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListMediaCutsInfoOperationCompleted);
            }
            this.InvokeAsync("ListMediaCutsInfo", new object[] {
                        strSessionID,
                        searchCriteria,
                        nMaxRow}, this.ListMediaCutsInfoOperationCompleted, userState);
        }
        
        private void OnListMediaCutsInfoOperationCompleted(object arg) {
            if ((this.ListMediaCutsInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListMediaCutsInfoCompleted(this, new ListMediaCutsInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/GetDetailedAirDateSession", RequestElementName="GetDetailedAirDateSession", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="GetDetailedAirDateSessionResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetDetailedAirDateSessionResult")]
        public System.Data.DataSet GetDetailedAirDate(string strSessionID, int nMediaInventoryId) {
            object[] results = this.Invoke("GetDetailedAirDate", new object[] {
                        strSessionID,
                        nMediaInventoryId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDetailedAirDate(string strSessionID, int nMediaInventoryId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDetailedAirDate", new object[] {
                        strSessionID,
                        nMediaInventoryId}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetDetailedAirDate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDetailedAirDateAsync(string strSessionID, int nMediaInventoryId) {
            this.GetDetailedAirDateAsync(strSessionID, nMediaInventoryId, null);
        }
        
        /// <remarks/>
        public void GetDetailedAirDateAsync(string strSessionID, int nMediaInventoryId, object userState) {
            if ((this.GetDetailedAirDateOperationCompleted == null)) {
                this.GetDetailedAirDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDetailedAirDateOperationCompleted);
            }
            this.InvokeAsync("GetDetailedAirDate", new object[] {
                        strSessionID,
                        nMediaInventoryId}, this.GetDetailedAirDateOperationCompleted, userState);
        }
        
        private void OnGetDetailedAirDateOperationCompleted(object arg) {
            if ((this.GetDetailedAirDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDetailedAirDateCompleted(this, new GetDetailedAirDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/ListPackageCutsInfoSession", RequestElementName="ListPackageCutsInfoSession", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="ListPackageCutsInfoSessionResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListPackageCutsInfoSessionResult")]
        public System.Data.DataSet ListPackageCutsInfo(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow) {
            object[] results = this.Invoke("ListPackageCutsInfo", new object[] {
                        strSessionID,
                        searchCriteria,
                        nMaxRow});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListPackageCutsInfo(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListPackageCutsInfo", new object[] {
                        strSessionID,
                        searchCriteria,
                        nMaxRow}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndListPackageCutsInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListPackageCutsInfoAsync(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow) {
            this.ListPackageCutsInfoAsync(strSessionID, searchCriteria, nMaxRow, null);
        }
        
        /// <remarks/>
        public void ListPackageCutsInfoAsync(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow, object userState) {
            if ((this.ListPackageCutsInfoOperationCompleted == null)) {
                this.ListPackageCutsInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListPackageCutsInfoOperationCompleted);
            }
            this.InvokeAsync("ListPackageCutsInfo", new object[] {
                        strSessionID,
                        searchCriteria,
                        nMaxRow}, this.ListPackageCutsInfoOperationCompleted, userState);
        }
        
        private void OnListPackageCutsInfoOperationCompleted(object arg) {
            if ((this.ListPackageCutsInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListPackageCutsInfoCompleted(this, new ListPackageCutsInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/ListPackageMediaInfoSession", RequestElementName="ListPackageMediaInfoSession", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="ListPackageMediaInfoSessionResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListPackageMediaInfoSessionResult")]
        public System.Data.DataSet ListPackageMediaInfo(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow) {
            object[] results = this.Invoke("ListPackageMediaInfo", new object[] {
                        strSessionID,
                        searchCriteria,
                        nMaxRow});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListPackageMediaInfo(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListPackageMediaInfo", new object[] {
                        strSessionID,
                        searchCriteria,
                        nMaxRow}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndListPackageMediaInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListPackageMediaInfoAsync(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow) {
            this.ListPackageMediaInfoAsync(strSessionID, searchCriteria, nMaxRow, null);
        }
        
        /// <remarks/>
        public void ListPackageMediaInfoAsync(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow, object userState) {
            if ((this.ListPackageMediaInfoOperationCompleted == null)) {
                this.ListPackageMediaInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListPackageMediaInfoOperationCompleted);
            }
            this.InvokeAsync("ListPackageMediaInfo", new object[] {
                        strSessionID,
                        searchCriteria,
                        nMaxRow}, this.ListPackageMediaInfoOperationCompleted, userState);
        }
        
        private void OnListPackageMediaInfoOperationCompleted(object arg) {
            if ((this.ListPackageMediaInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListPackageMediaInfoCompleted(this, new ListPackageMediaInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/SearchMediaAirDateSession", RequestElementName="SearchMediaAirDateSession", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="SearchMediaAirDateSessionResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SearchMediaAirDateSessionResult")]
        public string SearchMediaAirDate(string strSessionID, string strMediaHouseNumber, int nTune_value) {
            object[] results = this.Invoke("SearchMediaAirDate", new object[] {
                        strSessionID,
                        strMediaHouseNumber,
                        nTune_value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchMediaAirDate(string strSessionID, string strMediaHouseNumber, int nTune_value, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchMediaAirDate", new object[] {
                        strSessionID,
                        strMediaHouseNumber,
                        nTune_value}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSearchMediaAirDate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchMediaAirDateAsync(string strSessionID, string strMediaHouseNumber, int nTune_value) {
            this.SearchMediaAirDateAsync(strSessionID, strMediaHouseNumber, nTune_value, null);
        }
        
        /// <remarks/>
        public void SearchMediaAirDateAsync(string strSessionID, string strMediaHouseNumber, int nTune_value, object userState) {
            if ((this.SearchMediaAirDateOperationCompleted == null)) {
                this.SearchMediaAirDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchMediaAirDateOperationCompleted);
            }
            this.InvokeAsync("SearchMediaAirDate", new object[] {
                        strSessionID,
                        strMediaHouseNumber,
                        nTune_value}, this.SearchMediaAirDateOperationCompleted, userState);
        }
        
        private void OnSearchMediaAirDateOperationCompleted(object arg) {
            if ((this.SearchMediaAirDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchMediaAirDateCompleted(this, new SearchMediaAirDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/SearchPackageAirDateSession", RequestElementName="SearchPackageAirDateSession", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="SearchPackageAirDateSessionResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SearchPackageAirDateSessionResult")]
        public string SearchPackageAirDate(string strSessionID, string strPackageNumber, int nTune_value) {
            object[] results = this.Invoke("SearchPackageAirDate", new object[] {
                        strSessionID,
                        strPackageNumber,
                        nTune_value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchPackageAirDate(string strSessionID, string strPackageNumber, int nTune_value, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchPackageAirDate", new object[] {
                        strSessionID,
                        strPackageNumber,
                        nTune_value}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSearchPackageAirDate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchPackageAirDateAsync(string strSessionID, string strPackageNumber, int nTune_value) {
            this.SearchPackageAirDateAsync(strSessionID, strPackageNumber, nTune_value, null);
        }
        
        /// <remarks/>
        public void SearchPackageAirDateAsync(string strSessionID, string strPackageNumber, int nTune_value, object userState) {
            if ((this.SearchPackageAirDateOperationCompleted == null)) {
                this.SearchPackageAirDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchPackageAirDateOperationCompleted);
            }
            this.InvokeAsync("SearchPackageAirDate", new object[] {
                        strSessionID,
                        strPackageNumber,
                        nTune_value}, this.SearchPackageAirDateOperationCompleted, userState);
        }
        
        private void OnSearchPackageAirDateOperationCompleted(object arg) {
            if ((this.SearchPackageAirDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchPackageAirDateCompleted(this, new SearchPackageAirDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/SearchMediaInfoSession", RequestElementName="SearchMediaInfoSession", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="SearchMediaInfoSessionResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SearchMediaInfoSessionResult")]
        public System.Data.DataSet SearchMediaInfo(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow) {
            object[] results = this.Invoke("SearchMediaInfo", new object[] {
                        strSessionID,
                        searchCriteria,
                        nMaxRow});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchMediaInfo(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchMediaInfo", new object[] {
                        strSessionID,
                        searchCriteria,
                        nMaxRow}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndSearchMediaInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SearchMediaInfoAsync(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow) {
            this.SearchMediaInfoAsync(strSessionID, searchCriteria, nMaxRow, null);
        }
        
        /// <remarks/>
        public void SearchMediaInfoAsync(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow, object userState) {
            if ((this.SearchMediaInfoOperationCompleted == null)) {
                this.SearchMediaInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchMediaInfoOperationCompleted);
            }
            this.InvokeAsync("SearchMediaInfo", new object[] {
                        strSessionID,
                        searchCriteria,
                        nMaxRow}, this.SearchMediaInfoOperationCompleted, userState);
        }
        
        private void OnSearchMediaInfoOperationCompleted(object arg) {
            if ((this.SearchMediaInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchMediaInfoCompleted(this, new SearchMediaInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/SearchPackageInfoSession", RequestElementName="SearchPackageInfoSession", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="SearchPackageInfoSessionResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SearchPackageInfoSessionResult")]
        public System.Data.DataSet SearchPackageInfo(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow) {
            object[] results = this.Invoke("SearchPackageInfo", new object[] {
                        strSessionID,
                        searchCriteria,
                        nMaxRow});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchPackageInfo(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchPackageInfo", new object[] {
                        strSessionID,
                        searchCriteria,
                        nMaxRow}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndSearchPackageInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SearchPackageInfoAsync(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow) {
            this.SearchPackageInfoAsync(strSessionID, searchCriteria, nMaxRow, null);
        }
        
        /// <remarks/>
        public void SearchPackageInfoAsync(string strSessionID, SearchCriterion[] searchCriteria, int nMaxRow, object userState) {
            if ((this.SearchPackageInfoOperationCompleted == null)) {
                this.SearchPackageInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchPackageInfoOperationCompleted);
            }
            this.InvokeAsync("SearchPackageInfo", new object[] {
                        strSessionID,
                        searchCriteria,
                        nMaxRow}, this.SearchPackageInfoOperationCompleted, userState);
        }
        
        private void OnSearchPackageInfoOperationCompleted(object arg) {
            if ((this.SearchPackageInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchPackageInfoCompleted(this, new SearchPackageInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="ListMediaCutsInfo1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/ListMediaCutsInfo", RequestElementName="ListMediaCutsInfo", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="ListMediaCutsInfoResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListMediaCutsInfoResult")]
        public System.Data.DataSet ListMediaCutsInfo(SearchCriterion[] searchCriteria, int nMaxRow) {
            object[] results = this.Invoke("ListMediaCutsInfo1", new object[] {
                        searchCriteria,
                        nMaxRow});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListMediaCutsInfo1(SearchCriterion[] searchCriteria, int nMaxRow, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListMediaCutsInfo1", new object[] {
                        searchCriteria,
                        nMaxRow}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndListMediaCutsInfo1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListMediaCutsInfo1Async(SearchCriterion[] searchCriteria, int nMaxRow) {
            this.ListMediaCutsInfo1Async(searchCriteria, nMaxRow, null);
        }
        
        /// <remarks/>
        public void ListMediaCutsInfo1Async(SearchCriterion[] searchCriteria, int nMaxRow, object userState) {
            if ((this.ListMediaCutsInfo1OperationCompleted == null)) {
                this.ListMediaCutsInfo1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnListMediaCutsInfo1OperationCompleted);
            }
            this.InvokeAsync("ListMediaCutsInfo1", new object[] {
                        searchCriteria,
                        nMaxRow}, this.ListMediaCutsInfo1OperationCompleted, userState);
        }
        
        private void OnListMediaCutsInfo1OperationCompleted(object arg) {
            if ((this.ListMediaCutsInfo1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListMediaCutsInfo1Completed(this, new ListMediaCutsInfo1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="GetDetailedAirDate1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/GetDetailedAirDate", RequestElementName="GetDetailedAirDate", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="GetDetailedAirDateResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetDetailedAirDateResult")]
        public System.Data.DataSet GetDetailedAirDate(int nMediaInventoryId) {
            object[] results = this.Invoke("GetDetailedAirDate1", new object[] {
                        nMediaInventoryId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDetailedAirDate1(int nMediaInventoryId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDetailedAirDate1", new object[] {
                        nMediaInventoryId}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetDetailedAirDate1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDetailedAirDate1Async(int nMediaInventoryId) {
            this.GetDetailedAirDate1Async(nMediaInventoryId, null);
        }
        
        /// <remarks/>
        public void GetDetailedAirDate1Async(int nMediaInventoryId, object userState) {
            if ((this.GetDetailedAirDate1OperationCompleted == null)) {
                this.GetDetailedAirDate1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDetailedAirDate1OperationCompleted);
            }
            this.InvokeAsync("GetDetailedAirDate1", new object[] {
                        nMediaInventoryId}, this.GetDetailedAirDate1OperationCompleted, userState);
        }
        
        private void OnGetDetailedAirDate1OperationCompleted(object arg) {
            if ((this.GetDetailedAirDate1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDetailedAirDate1Completed(this, new GetDetailedAirDate1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="ListPackageCutsInfo1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/ListPackageCutsInfo", RequestElementName="ListPackageCutsInfo", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="ListPackageCutsInfoResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListPackageCutsInfoResult")]
        public System.Data.DataSet ListPackageCutsInfo(SearchCriterion[] searchCriteria, int nMaxRow) {
            object[] results = this.Invoke("ListPackageCutsInfo1", new object[] {
                        searchCriteria,
                        nMaxRow});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListPackageCutsInfo1(SearchCriterion[] searchCriteria, int nMaxRow, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListPackageCutsInfo1", new object[] {
                        searchCriteria,
                        nMaxRow}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndListPackageCutsInfo1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListPackageCutsInfo1Async(SearchCriterion[] searchCriteria, int nMaxRow) {
            this.ListPackageCutsInfo1Async(searchCriteria, nMaxRow, null);
        }
        
        /// <remarks/>
        public void ListPackageCutsInfo1Async(SearchCriterion[] searchCriteria, int nMaxRow, object userState) {
            if ((this.ListPackageCutsInfo1OperationCompleted == null)) {
                this.ListPackageCutsInfo1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnListPackageCutsInfo1OperationCompleted);
            }
            this.InvokeAsync("ListPackageCutsInfo1", new object[] {
                        searchCriteria,
                        nMaxRow}, this.ListPackageCutsInfo1OperationCompleted, userState);
        }
        
        private void OnListPackageCutsInfo1OperationCompleted(object arg) {
            if ((this.ListPackageCutsInfo1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListPackageCutsInfo1Completed(this, new ListPackageCutsInfo1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="ListPackageMediaInfo1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/ListPackageMediaInfo", RequestElementName="ListPackageMediaInfo", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="ListPackageMediaInfoResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListPackageMediaInfoResult")]
        public System.Data.DataSet ListPackageMediaInfo(SearchCriterion[] searchCriteria, int nMaxRow) {
            object[] results = this.Invoke("ListPackageMediaInfo1", new object[] {
                        searchCriteria,
                        nMaxRow});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListPackageMediaInfo1(SearchCriterion[] searchCriteria, int nMaxRow, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListPackageMediaInfo1", new object[] {
                        searchCriteria,
                        nMaxRow}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndListPackageMediaInfo1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListPackageMediaInfo1Async(SearchCriterion[] searchCriteria, int nMaxRow) {
            this.ListPackageMediaInfo1Async(searchCriteria, nMaxRow, null);
        }
        
        /// <remarks/>
        public void ListPackageMediaInfo1Async(SearchCriterion[] searchCriteria, int nMaxRow, object userState) {
            if ((this.ListPackageMediaInfo1OperationCompleted == null)) {
                this.ListPackageMediaInfo1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnListPackageMediaInfo1OperationCompleted);
            }
            this.InvokeAsync("ListPackageMediaInfo1", new object[] {
                        searchCriteria,
                        nMaxRow}, this.ListPackageMediaInfo1OperationCompleted, userState);
        }
        
        private void OnListPackageMediaInfo1OperationCompleted(object arg) {
            if ((this.ListPackageMediaInfo1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListPackageMediaInfo1Completed(this, new ListPackageMediaInfo1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="SearchMediaAirDate1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/SearchMediaAirDate", RequestElementName="SearchMediaAirDate", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="SearchMediaAirDateResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SearchMediaAirDateResult")]
        public string SearchMediaAirDate(string strMediaHouseNumber, int nTune_value) {
            object[] results = this.Invoke("SearchMediaAirDate1", new object[] {
                        strMediaHouseNumber,
                        nTune_value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchMediaAirDate1(string strMediaHouseNumber, int nTune_value, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchMediaAirDate1", new object[] {
                        strMediaHouseNumber,
                        nTune_value}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSearchMediaAirDate1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchMediaAirDate1Async(string strMediaHouseNumber, int nTune_value) {
            this.SearchMediaAirDate1Async(strMediaHouseNumber, nTune_value, null);
        }
        
        /// <remarks/>
        public void SearchMediaAirDate1Async(string strMediaHouseNumber, int nTune_value, object userState) {
            if ((this.SearchMediaAirDate1OperationCompleted == null)) {
                this.SearchMediaAirDate1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchMediaAirDate1OperationCompleted);
            }
            this.InvokeAsync("SearchMediaAirDate1", new object[] {
                        strMediaHouseNumber,
                        nTune_value}, this.SearchMediaAirDate1OperationCompleted, userState);
        }
        
        private void OnSearchMediaAirDate1OperationCompleted(object arg) {
            if ((this.SearchMediaAirDate1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchMediaAirDate1Completed(this, new SearchMediaAirDate1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="SearchPackageAirDate1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/SearchPackageAirDate", RequestElementName="SearchPackageAirDate", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="SearchPackageAirDateResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SearchPackageAirDateResult")]
        public string SearchPackageAirDate(string strPackageNumber, int nTune_value) {
            object[] results = this.Invoke("SearchPackageAirDate1", new object[] {
                        strPackageNumber,
                        nTune_value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchPackageAirDate1(string strPackageNumber, int nTune_value, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchPackageAirDate1", new object[] {
                        strPackageNumber,
                        nTune_value}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSearchPackageAirDate1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchPackageAirDate1Async(string strPackageNumber, int nTune_value) {
            this.SearchPackageAirDate1Async(strPackageNumber, nTune_value, null);
        }
        
        /// <remarks/>
        public void SearchPackageAirDate1Async(string strPackageNumber, int nTune_value, object userState) {
            if ((this.SearchPackageAirDate1OperationCompleted == null)) {
                this.SearchPackageAirDate1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchPackageAirDate1OperationCompleted);
            }
            this.InvokeAsync("SearchPackageAirDate1", new object[] {
                        strPackageNumber,
                        nTune_value}, this.SearchPackageAirDate1OperationCompleted, userState);
        }
        
        private void OnSearchPackageAirDate1OperationCompleted(object arg) {
            if ((this.SearchPackageAirDate1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchPackageAirDate1Completed(this, new SearchPackageAirDate1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/SearchFeatureAirDate", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SearchFeatureAirDate(int intFeatureMediaInventoryID, int nTune_value) {
            object[] results = this.Invoke("SearchFeatureAirDate", new object[] {
                        intFeatureMediaInventoryID,
                        nTune_value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchFeatureAirDate(int intFeatureMediaInventoryID, int nTune_value, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchFeatureAirDate", new object[] {
                        intFeatureMediaInventoryID,
                        nTune_value}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSearchFeatureAirDate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchFeatureAirDateAsync(int intFeatureMediaInventoryID, int nTune_value) {
            this.SearchFeatureAirDateAsync(intFeatureMediaInventoryID, nTune_value, null);
        }
        
        /// <remarks/>
        public void SearchFeatureAirDateAsync(int intFeatureMediaInventoryID, int nTune_value, object userState) {
            if ((this.SearchFeatureAirDateOperationCompleted == null)) {
                this.SearchFeatureAirDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchFeatureAirDateOperationCompleted);
            }
            this.InvokeAsync("SearchFeatureAirDate", new object[] {
                        intFeatureMediaInventoryID,
                        nTune_value}, this.SearchFeatureAirDateOperationCompleted, userState);
        }
        
        private void OnSearchFeatureAirDateOperationCompleted(object arg) {
            if ((this.SearchFeatureAirDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchFeatureAirDateCompleted(this, new SearchFeatureAirDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="SearchMediaInfo1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/SearchMediaInfo", RequestElementName="SearchMediaInfo", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="SearchMediaInfoResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SearchMediaInfoResult")]
        public System.Data.DataSet SearchMediaInfo(SearchCriterion[] searchCriteria, int nMaxRow) {
            object[] results = this.Invoke("SearchMediaInfo1", new object[] {
                        searchCriteria,
                        nMaxRow});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchMediaInfo1(SearchCriterion[] searchCriteria, int nMaxRow, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchMediaInfo1", new object[] {
                        searchCriteria,
                        nMaxRow}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndSearchMediaInfo1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SearchMediaInfo1Async(SearchCriterion[] searchCriteria, int nMaxRow) {
            this.SearchMediaInfo1Async(searchCriteria, nMaxRow, null);
        }
        
        /// <remarks/>
        public void SearchMediaInfo1Async(SearchCriterion[] searchCriteria, int nMaxRow, object userState) {
            if ((this.SearchMediaInfo1OperationCompleted == null)) {
                this.SearchMediaInfo1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchMediaInfo1OperationCompleted);
            }
            this.InvokeAsync("SearchMediaInfo1", new object[] {
                        searchCriteria,
                        nMaxRow}, this.SearchMediaInfo1OperationCompleted, userState);
        }
        
        private void OnSearchMediaInfo1OperationCompleted(object arg) {
            if ((this.SearchMediaInfo1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchMediaInfo1Completed(this, new SearchMediaInfo1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="SearchPackageInfo1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.pbstest.org/SAWebService/SearchPackageInfo", RequestElementName="SearchPackageInfo", RequestNamespace="http://webservices.pbstest.org/SAWebService", ResponseElementName="SearchPackageInfoResponse", ResponseNamespace="http://webservices.pbstest.org/SAWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SearchPackageInfoResult")]
        public System.Data.DataSet SearchPackageInfo(SearchCriterion[] searchCriteria, int nMaxRow) {
            object[] results = this.Invoke("SearchPackageInfo1", new object[] {
                        searchCriteria,
                        nMaxRow});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchPackageInfo1(SearchCriterion[] searchCriteria, int nMaxRow, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchPackageInfo1", new object[] {
                        searchCriteria,
                        nMaxRow}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndSearchPackageInfo1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SearchPackageInfo1Async(SearchCriterion[] searchCriteria, int nMaxRow) {
            this.SearchPackageInfo1Async(searchCriteria, nMaxRow, null);
        }
        
        /// <remarks/>
        public void SearchPackageInfo1Async(SearchCriterion[] searchCriteria, int nMaxRow, object userState) {
            if ((this.SearchPackageInfo1OperationCompleted == null)) {
                this.SearchPackageInfo1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchPackageInfo1OperationCompleted);
            }
            this.InvokeAsync("SearchPackageInfo1", new object[] {
                        searchCriteria,
                        nMaxRow}, this.SearchPackageInfo1OperationCompleted, userState);
        }
        
        private void OnSearchPackageInfo1OperationCompleted(object arg) {
            if ((this.SearchPackageInfo1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchPackageInfo1Completed(this, new SearchPackageInfo1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.pbstest.org/SAWebService")]
    public partial class UserProfile : UserProfileBase {
        
        private string[] oOperatingGroupField;
        
        private short nOperatingUnitField;
        
        private short nUnitTypeField;
        
        private short nRoleField;
        
        private string sExternalEmailField;
        
        private string sPhoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("sCode")]
        public string[] oOperatingGroup {
            get {
                return this.oOperatingGroupField;
            }
            set {
                this.oOperatingGroupField = value;
            }
        }
        
        /// <remarks/>
        public short nOperatingUnit {
            get {
                return this.nOperatingUnitField;
            }
            set {
                this.nOperatingUnitField = value;
            }
        }
        
        /// <remarks/>
        public short nUnitType {
            get {
                return this.nUnitTypeField;
            }
            set {
                this.nUnitTypeField = value;
            }
        }
        
        /// <remarks/>
        public short nRole {
            get {
                return this.nRoleField;
            }
            set {
                this.nRoleField = value;
            }
        }
        
        /// <remarks/>
        public string sExternalEmail {
            get {
                return this.sExternalEmailField;
            }
            set {
                this.sExternalEmailField = value;
            }
        }
        
        /// <remarks/>
        public string sPhoneNumber {
            get {
                return this.sPhoneNumberField;
            }
            set {
                this.sPhoneNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserProfile))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.pbstest.org/SAWebService")]
    public partial class UserProfileBase {
        
        private string sConnectIdField;
        
        private string sFirstNameField;
        
        private string sLastNameField;
        
        /// <remarks/>
        public string sConnectId {
            get {
                return this.sConnectIdField;
            }
            set {
                this.sConnectIdField = value;
            }
        }
        
        /// <remarks/>
        public string sFirstName {
            get {
                return this.sFirstNameField;
            }
            set {
                this.sFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string sLastName {
            get {
                return this.sLastNameField;
            }
            set {
                this.sLastNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.pbstest.org/SAWebService")]
    public partial class SearchCriterion {
        
        private string searchFieldField;
        
        private string searchValueField;
        
        /// <remarks/>
        public string SearchField {
            get {
                return this.searchFieldField;
            }
            set {
                this.searchFieldField = value;
            }
        }
        
        /// <remarks/>
        public string SearchValue {
            get {
                return this.searchValueField;
            }
            set {
                this.searchValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CloseSessionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void OpenSessionCompletedEventHandler(object sender, OpenSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OpenSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OpenSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ListMediaCutsInfoCompletedEventHandler(object sender, ListMediaCutsInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListMediaCutsInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListMediaCutsInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDetailedAirDateCompletedEventHandler(object sender, GetDetailedAirDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDetailedAirDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDetailedAirDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ListPackageCutsInfoCompletedEventHandler(object sender, ListPackageCutsInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListPackageCutsInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListPackageCutsInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ListPackageMediaInfoCompletedEventHandler(object sender, ListPackageMediaInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListPackageMediaInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListPackageMediaInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchMediaAirDateCompletedEventHandler(object sender, SearchMediaAirDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchMediaAirDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchMediaAirDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchPackageAirDateCompletedEventHandler(object sender, SearchPackageAirDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchPackageAirDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchPackageAirDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchMediaInfoCompletedEventHandler(object sender, SearchMediaInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchMediaInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchMediaInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchPackageInfoCompletedEventHandler(object sender, SearchPackageInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchPackageInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchPackageInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ListMediaCutsInfo1CompletedEventHandler(object sender, ListMediaCutsInfo1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListMediaCutsInfo1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListMediaCutsInfo1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDetailedAirDate1CompletedEventHandler(object sender, GetDetailedAirDate1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDetailedAirDate1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDetailedAirDate1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ListPackageCutsInfo1CompletedEventHandler(object sender, ListPackageCutsInfo1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListPackageCutsInfo1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListPackageCutsInfo1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ListPackageMediaInfo1CompletedEventHandler(object sender, ListPackageMediaInfo1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListPackageMediaInfo1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListPackageMediaInfo1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchMediaAirDate1CompletedEventHandler(object sender, SearchMediaAirDate1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchMediaAirDate1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchMediaAirDate1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchPackageAirDate1CompletedEventHandler(object sender, SearchPackageAirDate1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchPackageAirDate1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchPackageAirDate1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchFeatureAirDateCompletedEventHandler(object sender, SearchFeatureAirDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchFeatureAirDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchFeatureAirDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchMediaInfo1CompletedEventHandler(object sender, SearchMediaInfo1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchMediaInfo1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchMediaInfo1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchPackageInfo1CompletedEventHandler(object sender, SearchPackageInfo1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchPackageInfo1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchPackageInfo1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591