REM XSD
fc %1\xsd\LoadAlliantContractModelsDataSet.xsd  %2\xsd\LoadAlliantContractModelsDataSet.xsd
fc %1\xsd\LoadAspectRatioTypeDataSet.xsd  %2\xsd\LoadAspectRatioTypeDataSet.xsd
fc %1\xsd\LoadAssetCategoryDataSet.xsd  %2\xsd\LoadAssetCategoryDataSet.xsd
fc %1\xsd\LoadAudioTypeDataSet.xsd  %2\xsd\LoadAudioTypeDataSet.xsd
fc %1\xsd\LoadBillToContactDataSet.xsd  %2\xsd\LoadBillToContactDataSet.xsd
fc %1\xsd\LoadBillToDataSet.xsd  %2\xsd\LoadBillToDataSet.xsd
fc %1\xsd\LoadCaptionVendorDataSet.xsd  %2\xsd\LoadCaptionVendorDataSet.xsd
fc %1\xsd\LoadCompanyDataSet.xsd  %2\xsd\LoadCompanyDataSet.xsd
fc %1\xsd\LoadContactTypeDataSet.xsd  %2\xsd\LoadContactTypeDataSet.xsd
fc %1\xsd\LoadCutItemTypeDataSet.xsd  %2\xsd\LoadCutItemTypeDataSet.xsd
fc %1\xsd\LoadDisclaimerDataSet.xsd  %2\xsd\LoadDisclaimerDataSet.xsd
fc %1\xsd\LoadDistributorsDataSet.xsd  %2\xsd\LoadDistributorsDataSet.xsd
fc %1\xsd\LoadFundersDataSet.xsd  %2\xsd\LoadFundersDataSet.xsd
fc %1\xsd\LoadFunderTypeDataSet.xsd  %2\xsd\LoadFunderTypeDataSet.xsd
fc %1\xsd\LoadGenreDataSet.xsd  %2\xsd\LoadGenreDataSet.xsd
fc %1\xsd\LoadHighDefTypeDataSet.xsd  %2\xsd\LoadHighDefTypeDataSet.xsd
fc %1\xsd\LoadKeywordsDataSet.xsd  %2\xsd\LoadKeywordsDataSet.xsd
fc %1\xsd\LoadLanguageDataSet.xsd  %2\xsd\LoadLanguageDataSet.xsd
fc %1\xsd\LoadLocalUnderwritingDataSet.xsd  %2\xsd\LoadLocalUnderwritingDataSet.xsd
fc %1\xsd\LoadMediaFeatureClassDataSet.xsd  %2\xsd\LoadMediaFeatureClassDataSet.xsd
fc %1\xsd\LoadMediaFeatureDataSet.xsd  %2\xsd\LoadMediaFeatureDataSet.xsd
fc %1\xsd\LoadMediaFormatTypeDataSet.xsd  %2\xsd\LoadMediaFormatTypeDataSet.xsd
fc %1\xsd\LoadMediaInventoryTypeDataSet.xsd  %2\xsd\LoadMediaInventoryTypeDataSet.xsd
fc %1\xsd\LoadMediaStatusDataSet.xsd  %2\xsd\LoadMediaStatusDataSet.xsd
fc %1\xsd\LoadOacPostOfferDescriptionTypeDataSet.xsd  %2\xsd\LoadOacPostOfferDescriptionTypeDataSet.xsd
fc %1\xsd\LoadOacPreOfferDescriptionTypeDataSet.xsd  %2\xsd\LoadOacPreOfferDescriptionTypeDataSet.xsd
fc %1\xsd\LoadPackageTypeDataSet.xsd  %2\xsd\LoadPackageTypeDataSet.xsd
fc %1\xsd\LoadPBSProgramTypeDataSet.xsd  %2\xsd\LoadPBSProgramTypeDataSet.xsd
fc %1\xsd\LoadPlayRuleDataSet.xsd  %2\xsd\LoadPlayRuleDataSet.xsd
fc %1\xsd\LoadProgramTypeDataSet.xsd  %2\xsd\LoadProgramTypeDataSet.xsd
fc %1\xsd\LoadRatingDataSet.xsd  %2\xsd\LoadRatingDataSet.xsd
fc %1\xsd\LoadSchoolRightsDataSet.xsd  %2\xsd\LoadSchoolRightsDataSet.xsd
fc %1\xsd\LoadStationsDataSet.xsd  %2\xsd\LoadStationsDataSet.xsd
fc %1\xsd\LoadSurroundSoundTypeDataSet.xsd  %2\xsd\LoadSurroundSoundTypeDataSet.xsd
fc %1\xsd\LoadTalentRolesDataSet.xsd  %2\xsd\LoadTalentRolesDataSet.xsd
fc %1\xsd\LoadUplinksDataSet.xsd  %2\xsd\LoadUplinksDataSet.xsd
fc %1\xsd\LoadVCHIPValuesDataSet.xsd  %2\xsd\LoadVCHIPValuesDataSet.xsd
fc %1\xsd\LoadVersionFormatAndTypeDataSet.xsd  %2\xsd\LoadVersionFormatAndTypeDataSet.xsd
fc %1\xsd\LoadVideoFormatDataSet.xsd  %2\xsd\LoadVideoFormatDataSet.xsd

REM XSLT
fc %1\xslt\LoadAlliantContractModels.xslt  %2\xslt\LoadAlliantContractModels.xslt
fc %1\xslt\LoadAspectRatioType.xslt  %2\xslt\LoadAspectRatioType.xslt
fc %1\xslt\LoadAssetCategory.xslt  %2\xslt\LoadAssetCategory.xslt
fc %1\xslt\LoadAudioType.xslt  %2\xslt\LoadAudioType.xslt
fc %1\xslt\LoadBillTo.xslt  %2\xslt\LoadBillTo.xslt
fc %1\xslt\LoadBillToContact.xslt  %2\xslt\LoadBillToContact.xslt
fc %1\xslt\LoadCaptionVendor.xslt  %2\xslt\LoadCaptionVendor.xslt
fc %1\xslt\LoadCompany.xslt  %2\xslt\LoadCompany.xslt
fc %1\xslt\LoadContactType.xslt  %2\xslt\LoadContactType.xslt
fc %1\xslt\LoadCutItemType.xslt  %2\xslt\LoadCutItemType.xslt
fc %1\xslt\LoadDisclaimer.xslt  %2\xslt\LoadDisclaimer.xslt
fc %1\xslt\LoadDistributors.xslt  %2\xslt\LoadDistributors.xslt
fc %1\xslt\LoadFunders.xslt  %2\xslt\LoadFunders.xslt
fc %1\xslt\LoadFunderType.xslt  %2\xslt\LoadFunderType.xslt
fc %1\xslt\LoadGenre.xslt  %2\xslt\LoadGenre.xslt
fc %1\xslt\LoadHighDefType.xslt  %2\xslt\LoadHighDefType.xslt
fc %1\xslt\LoadKeywords.xslt  %2\xslt\LoadKeywords.xslt
fc %1\xslt\LoadLanguage.xslt  %2\xslt\LoadLanguage.xslt
fc %1\xslt\LoadLocalUnderwriting.xslt  %2\xslt\LoadLocalUnderwriting.xslt
fc %1\xslt\LoadMediaFeature.xslt  %2\xslt\LoadMediaFeature.xslt
fc %1\xslt\LoadMediaFeatureClass.xslt  %2\xslt\LoadMediaFeatureClass.xslt
fc %1\xslt\LoadMediaFormatType.xslt  %2\xslt\LoadMediaFormatType.xslt
fc %1\xslt\LoadMediaStatus.xslt  %2\xslt\LoadMediaStatus.xslt
fc %1\xslt\LoadMediaInventoryType.xslt  %2\xslt\LoadMediaInventoryType.xslt
fc %1\xslt\LoadOacPostOfferDescriptionType.xslt  %2\xslt\LoadOacPostOfferDescriptionType.xslt
fc %1\xslt\LoadOacPreOfferDescriptionType.xslt  %2\xslt\LoadOacPreOfferDescriptionType.xslt
fc %1\xslt\LoadPackageType.xslt  %2\xslt\LoadPackageType.xslt
fc %1\xslt\LoadPBSProgramType.xslt  %2\xslt\LoadPBSProgramType.xslt
fc %1\xslt\LoadPlayRule.xslt  %2\xslt\LoadPlayRule.xslt
fc %1\xslt\LoadProgramType.xslt  %2\xslt\LoadProgramType.xslt
fc %1\xslt\LoadRating.xslt  %2\xslt\LoadRating.xslt
fc %1\xslt\LoadSchoolRights.xslt  %2\xslt\LoadSchoolRights.xslt
fc %1\xslt\LoadStations.xslt  %2\xslt\LoadStations.xslt
fc %1\xslt\LoadSurroundSoundType.xslt  %2\xslt\LoadSurroundSoundType.xslt
fc %1\xslt\LoadTalentRoles.xslt  %2\xslt\LoadTalentRoles.xslt
fc %1\xslt\LoadUplinks.xslt  %2\xslt\LoadUplinks.xslt
fc %1\xslt\LoadVCHIPValues.xslt  %2\xslt\LoadVCHIPValues.xslt
fc %1\xslt\LoadVersionFormatAndType.xslt  %2\xslt\LoadVersionFormatAndType.xslt
fc %1\xslt\LoadVideoFormat.xslt  %2\xslt\LoadVideoFormat.xslt

REM XSLTClass
fc %1\xsltclass\LoadAlliantContractModelsClass.cs  %2\xsltclass\LoadAlliantContractModelsClass.cs
fc %1\xsltclass\LoadAspectRatioTypeClass.cs  %2\xsltclass\LoadAspectRatioTypeClass.cs
fc %1\xsltclass\LoadAssetCategoryClass.cs  %2\xsltclass\LoadAssetCategoryClass.cs
fc %1\xsltclass\LoadAudioTypeClass.cs  %2\xsltclass\LoadAudioTypeClass.cs
fc %1\xsltclass\LoadBillToClass.cs  %2\xsltclass\LoadBillToClass.cs
fc %1\xsltclass\LoadBillToContactClass.cs  %2\xsltclass\LoadBillToContactClass.cs
fc %1\xsltclass\LoadCaptionVendorClass.cs  %2\xsltclass\LoadCaptionVendorClass.cs
fc %1\xsltclass\LoadCompanyClass.cs  %2\xsltclass\LoadCompanyClass.cs
fc %1\xsltclass\LoadContactTypeClass.cs  %2\xsltclass\LoadContactTypeClass.cs
fc %1\xsltclass\LoadCutItemTypeClass.cs  %2\xsltclass\LoadCutItemTypeClass.cs
fc %1\xsltclass\LoadDisclaimerClass.cs  %2\xsltclass\LoadDisclaimerClass.cs
fc %1\xsltclass\LoadDistributorsClass.cs  %2\xsltclass\LoadDistributorsClass.cs
fc %1\xsltclass\LoadFundersClass.cs  %2\xsltclass\LoadFundersClass.cs
fc %1\xsltclass\LoadFunderTypeClass.cs  %2\xsltclass\LoadFunderTypeClass.cs
fc %1\xsltclass\LoadGenreClass.cs  %2\xsltclass\LoadGenreClass.cs
fc %1\xsltclass\LoadHighDefTypeClass.cs  %2\xsltclass\LoadHighDefTypeClass.cs
fc %1\xsltclass\LoadKeywordsClass.cs  %2\xsltclass\LoadKeywordsClass.cs
fc %1\xsltclass\LoadLanguageClass.cs  %2\xsltclass\LoadLanguageClass.cs
fc %1\xsltclass\LoadLocalUnderwritingClass.cs  %2\xsltclass\LoadLocalUnderwritingClass.cs
fc %1\xsltclass\LoadMediaFeatureClass.cs  %2\xsltclass\LoadMediaFeatureClass.cs
fc %1\xsltclass\LoadMediaFeatureClassClass.cs  %2\xsltclass\LoadMediaFeatureClassClass.cs
fc %1\xsltclass\LoadMediaFormatTypeClass.cs  %2\xsltclass\LoadMediaFormatTypeClass.cs
fc %1\xsltclass\LoadMediaInventoryTypeClass.cs  %2\xsltclass\LoadMediaInventoryTypeClass.cs
fc %1\xsltclass\LoadMediaStatusClass.cs  %2\xsltclass\LoadMediaStatusClass.cs
fc %1\xsltclass\LoadOacPostOfferDescriptionTypeClass.cs  %2\xsltclass\LoadOacPostOfferDescriptionTypeClass.cs
fc %1\xsltclass\LoadOacPreOfferDescriptionTypeClass.cs  %2\xsltclass\LoadOacPreOfferDescriptionTypeClass.cs
fc %1\xsltclass\LoadPackageTypeClass.cs  %2\xsltclass\LoadPackageTypeClass.cs
fc %1\xsltclass\LoadPBSProgramTypeClass.cs  %2\xsltclass\LoadPBSProgramTypeClass.cs
fc %1\xsltclass\LoadPlayRuleClass.cs  %2\xsltclass\LoadPlayRuleClass.cs
fc %1\xsltclass\LoadProgramTypeClass.cs  %2\xsltclass\LoadProgramTypeClass.cs
fc %1\xsltclass\LoadRatingClass.cs  %2\xsltclass\LoadRatingClass.cs
fc %1\xsltclass\LoadSchoolRightsClass.cs  %2\xsltclass\LoadSchoolRightsClass.cs
fc %1\xsltclass\LoadStationsClass.cs  %2\xsltclass\LoadStationsClass.cs
fc %1\xsltclass\LoadSurroundSoundTypeClass.cs  %2\xsltclass\LoadSurroundSoundTypeClass.cs
fc %1\xsltclass\LoadTalentRolesClass.cs  %2\xsltclass\LoadTalentRolesClass.cs
fc %1\xsltclass\LoadUplinksClass.cs  %2\xsltclass\LoadUplinksClass.cs
fc %1\xsltclass\LoadVCHIPValuesClass.cs  %2\xsltclass\LoadVCHIPValuesClass.cs
fc %1\xsltclass\LoadVersionFormatAndTypeClass.cs  %2\xsltclass\LoadVersionFormatAndTypeClass.cs
fc %1\xsltclass\LoadVideoFormatClass.cs  %2\xsltclass\LoadVideoFormatClass.cs






